// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#ifndef UI_BOOTSCREEN_H
#define UI_BOOTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_bootscreen
extern void ui_bootscreen_screen_init(void);
extern void ui_bootscreen_screen_destroy(void);
extern lv_obj_t * ui_bootscreen;
extern lv_obj_t * ui_logoboot;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

