// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void abrirajustes(lv_event_t * e);
void cerrarajustes(lv_event_t * e);
void opcionesdrop(lv_event_t * e);
void themesitch(lv_event_t * e);
void cambiarpantalla(lv_event_t * e);
void cambiardatos(lv_event_t * e);

void lessrpm_(lv_event_t * e);
void morerpm_(lv_event_t * e);
void lessdesp(lv_event_t * e);
void moredesp(lv_event_t * e);
void rpmdisplay(lv_event_t * e);
void lessdiffrpm(lv_event_t * e);
void morediffrpm(lv_event_t * e);

void lessvbatttoohigh(lv_event_t * e);
void morevbatttoohigh(lv_event_t * e);
void lessvbatthigh(lv_event_t * e);
void morebvbatthigh(lv_event_t * e);
void lessvbattlow(lv_event_t * e);
void morevbattlow(lv_event_t * e);

void lesswaterhot(lv_event_t * e);
void mroewaterhot(lv_event_t * e);
void lesswatermild(lv_event_t * e);
void morewatermild(lv_event_t * e);
void lesswatercold(lv_event_t * e);
void morewatercold(lv_event_t * e);

void lessoilhot(lv_event_t * e);
void moreoilhot(lv_event_t * e);
void lessoilmild(lv_event_t * e);
void moreoilmild(lv_event_t * e);
void lessoilcold(lv_event_t * e);
void moreoilcold(lv_event_t * e);

void lessoilptoohigh(lv_event_t * e);
void moreoilptoohigh(lv_event_t * e);
void lessoilphigh(lv_event_t * e);
void moreoilphigh(lv_event_t * e);
void lessoilplow(lv_event_t * e);
void moreoilplow(lv_event_t * e);

void lessfuelptoohigh(lv_event_t * e);
void morefuelptoohigh(lv_event_t * e);
void lessfuelphigh(lv_event_t * e);
void morefuelphigh(lv_event_t * e);
void lessfuelp(lv_event_t * e);
void morefuelplow(lv_event_t * e);

void refresh_ui_values();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif