// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_barcontainer;
extern lv_obj_t * ui_rpm0;
extern lv_obj_t * ui_rpmt0;
extern lv_obj_t * ui_rpm1;
extern lv_obj_t * ui_rpm2;
extern lv_obj_t * ui_rpmt1;
extern lv_obj_t * ui_rpm3;
extern lv_obj_t * ui_rpm4;
extern lv_obj_t * ui_rpmt2;
extern lv_obj_t * ui_rpm5;
extern lv_obj_t * ui_rpm6;
extern lv_obj_t * ui_rpmt3;
extern lv_obj_t * ui_rpm7;
extern lv_obj_t * ui_rpm8;
extern lv_obj_t * ui_rpmt4;
extern lv_obj_t * ui_rpm9;
extern lv_obj_t * ui_rpm10;
extern lv_obj_t * ui_rpmt5;
extern lv_obj_t * ui_rpm11;
extern lv_obj_t * ui_rpm12;
extern lv_obj_t * ui_rpmt6;
extern lv_obj_t * ui_rpm13;
extern lv_obj_t * ui_rpmt16;
extern lv_obj_t * ui_rpmt7;
extern lv_obj_t * ui_rpmt8;
extern lv_obj_t * ui_rpmt9;
extern lv_obj_t * ui_rpmt10;
extern lv_obj_t * ui_rpmt11;
extern lv_obj_t * ui_rpmt12;
extern lv_obj_t * ui_rpmbaja1;
extern lv_obj_t * ui_rpmbaja2;
extern lv_obj_t * ui_rpmbaja3;
extern lv_obj_t * ui_rpmbaja4;
extern lv_obj_t * ui_rpmbaja5;
extern lv_obj_t * ui_rpmbaja6;
extern lv_obj_t * ui_rpmbaja7;
extern lv_obj_t * ui_tiraledsrpmcontainer;
extern lv_obj_t * ui_led0;
extern lv_obj_t * ui_led1;
extern lv_obj_t * ui_led2;
extern lv_obj_t * ui_led3;
extern lv_obj_t * ui_led4;
extern lv_obj_t * ui_led5;
extern lv_obj_t * ui_led6;
extern lv_obj_t * ui_led7;
extern lv_obj_t * ui_led8;
extern lv_obj_t * ui_led9;
extern lv_obj_t * ui_led10;
extern lv_obj_t * ui_led11;
extern lv_obj_t * ui_led12;
extern lv_obj_t * ui_led13;
extern lv_obj_t * ui_led14;
extern lv_obj_t * ui_barrpm;
extern lv_obj_t * ui_rpma;
extern lv_obj_t * ui_rpmb;
extern lv_obj_t * ui_rpmname;
extern lv_obj_t * ui_rpm;
extern lv_obj_t * ui_oiltpanel;
extern lv_obj_t * ui_oilt;
extern lv_obj_t * ui_oiltname;
extern lv_obj_t * ui_oiltseparator;
extern lv_obj_t * ui_oilppanel;
extern lv_obj_t * ui_oilp;
extern lv_obj_t * ui_oilpseparator;
extern lv_obj_t * ui_oilpname;
extern lv_obj_t * ui_fuelppanel;
extern lv_obj_t * ui_fuelp;
extern lv_obj_t * ui_fuelpseparator;
extern lv_obj_t * ui_fuelpname;
extern lv_obj_t * ui_lambdapanel;
extern lv_obj_t * ui_lambda;
extern lv_obj_t * ui_lambdaname;
extern lv_obj_t * ui_lambdaseparator;
extern lv_obj_t * ui_watertpanel;
extern lv_obj_t * ui_watert;
extern lv_obj_t * ui_watertseparator;
extern lv_obj_t * ui_watertname;
extern lv_obj_t * ui_sdownpanel;
extern lv_obj_t * ui_sdownname;
extern lv_obj_t * ui_sdown;
extern lv_obj_t * ui_sdownseparator;
extern lv_obj_t * ui_vbatpanel;
extern lv_obj_t * ui_vbat;
extern lv_obj_t * ui_vbatseparator;
extern lv_obj_t * ui_vbatname;
extern lv_obj_t * ui_fanpanel;
extern lv_obj_t * ui_fanname;
extern lv_obj_t * ui_fan;
extern lv_obj_t * ui_fanseparator;
extern lv_obj_t * ui_neutralpanel;
extern lv_obj_t * ui_neutral;
extern lv_obj_t * ui_warmuppanel;
extern lv_obj_t * ui_warmup;
extern void ui_event_botonshowajustes(lv_event_t * e);
extern lv_obj_t * ui_botonshowajustes;
extern void ui_event_ajustesboton(lv_event_t * e);
extern lv_obj_t * ui_ajustesboton;
extern lv_obj_t * ui_ajustesnombre;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

