// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_aux1panel;
extern lv_obj_t * ui_aux1name;
extern lv_obj_t * ui_aux1;
extern lv_obj_t * ui_aux1separator;
extern lv_obj_t * ui_aux3panel;
extern lv_obj_t * ui_aux3name;
extern lv_obj_t * ui_aux3;
extern lv_obj_t * ui_aux3separator;
extern lv_obj_t * ui_aux4panel;
extern lv_obj_t * ui_aux4name;
extern lv_obj_t * ui_aux4;
extern lv_obj_t * ui_aux4separator;
extern lv_obj_t * ui_aux5panel;
extern lv_obj_t * ui_aux5name;
extern lv_obj_t * ui_aux5;
extern lv_obj_t * ui_aux5separator;
extern lv_obj_t * ui_aux6panel;
extern lv_obj_t * ui_aux6name;
extern lv_obj_t * ui_aux6;
extern lv_obj_t * ui_aux6separator;
extern lv_obj_t * ui_aux7panel;
extern lv_obj_t * ui_aux7name;
extern lv_obj_t * ui_aux7;
extern lv_obj_t * ui_aux7separator;
extern lv_obj_t * ui_aux8panel;
extern lv_obj_t * ui_aux8name;
extern lv_obj_t * ui_aux8;
extern lv_obj_t * ui_aux8separator;
extern lv_obj_t * ui_dig1panel;
extern lv_obj_t * ui_dig1name;
extern lv_obj_t * ui_dig1;
extern lv_obj_t * ui_dig1separator;
extern lv_obj_t * ui_throttlepanel;
extern lv_obj_t * ui_throttlename;
extern lv_obj_t * ui_throttle;
extern lv_obj_t * ui_throttleseparator;
extern lv_obj_t * ui_nousepanel;
extern lv_obj_t * ui_nousename;
extern lv_obj_t * ui_nouse;
extern lv_obj_t * ui_nouseseparator;
extern lv_obj_t * ui_lambdtrgapanel;
extern lv_obj_t * ui_lambdatrgname;
extern lv_obj_t * ui_lambdatrg;
extern lv_obj_t * ui_lambdatrgseparator;
extern lv_obj_t * ui_mappanel;
extern lv_obj_t * ui_mapname;
extern lv_obj_t * ui_map;
extern lv_obj_t * ui_mapseparator;
extern lv_obj_t * ui_brakepanel;
extern lv_obj_t * ui_brakename;
extern lv_obj_t * ui_brake;
extern lv_obj_t * ui_brakeseparator;
extern void ui_event_botonshowajustes2(lv_event_t * e);
extern lv_obj_t * ui_botonshowajustes2;
extern void ui_event_ajustesboton2(lv_event_t * e);
extern lv_obj_t * ui_ajustesboton2;
extern lv_obj_t * ui_ajustesnombre2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

