// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#ifndef UI_SETTINGSCREEN_H
#define UI_SETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingscreen
extern void ui_settingscreen_screen_init(void);
extern void ui_settingscreen_screen_destroy(void);
extern lv_obj_t * ui_settingscreen;
extern lv_obj_t * ui_cross1;
extern lv_obj_t * ui_cross2;
extern void ui_event_cerrarajustesboton(lv_event_t * e);
extern lv_obj_t * ui_cerrarajustesboton;
extern lv_obj_t * ui_ajustesname;
extern lv_obj_t * ui_ajustesseparator;
extern lv_obj_t * ui_opcionname;
extern void ui_event_opciondrop(lv_event_t * e);
extern lv_obj_t * ui_opciondrop;
extern lv_obj_t * ui_settingsmain;
extern lv_obj_t * ui_modooscuroname;
extern void ui_event_modooscuoswitch(lv_event_t * e);
extern lv_obj_t * ui_modooscuoswitch;
extern lv_obj_t * ui_pantallaname;
extern void ui_event_pantalladrop(lv_event_t * e);
extern lv_obj_t * ui_pantalladrop;
extern lv_obj_t * ui_recepciondatosname;
extern void ui_event_recepciondatosdrop(lv_event_t * e);
extern lv_obj_t * ui_recepciondatosdrop;
extern lv_obj_t * ui_settingsrpm;
extern lv_obj_t * ui_rpmfinalname;
extern lv_obj_t * ui_rpmfinalvalue;
extern void ui_event_lessrpm(lv_event_t * e);
extern lv_obj_t * ui_lessrpm;
extern lv_obj_t * ui_lessrpmname;
extern void ui_event_morerpm(lv_event_t * e);
extern lv_obj_t * ui_morerpm;
extern lv_obj_t * ui_morerpmname;
extern lv_obj_t * ui_desplazamientoname;
extern lv_obj_t * ui_desplazamientovalue;
extern void ui_event_lessdesp(lv_event_t * e);
extern lv_obj_t * ui_lessdesp;
extern lv_obj_t * ui_lessdespname;
extern void ui_event_moredesp(lv_event_t * e);
extern lv_obj_t * ui_moredesp;
extern lv_obj_t * ui_moredespname;
extern lv_obj_t * ui_rpmdisplayname;
extern void ui_event_rpmdisplaydrop(lv_event_t * e);
extern lv_obj_t * ui_rpmdisplaydrop;
extern lv_obj_t * ui_diffrpmname;
extern lv_obj_t * ui_diffrpmvalue;
extern void ui_event_lessdiffrpm(lv_event_t * e);
extern lv_obj_t * ui_lessdiffrpm;
extern lv_obj_t * ui_lessdiffrpmname;
extern void ui_event_morediffrpm(lv_event_t * e);
extern lv_obj_t * ui_morediffrpm;
extern lv_obj_t * ui_morediffrpmname;
extern lv_obj_t * ui_settingsvbatt;
extern lv_obj_t * ui_vbatttoohigh;
extern lv_obj_t * ui_vbatttoohighvalue;
extern void ui_event_lessvbatttoohigh(lv_event_t * e);
extern lv_obj_t * ui_lessvbatttoohigh;
extern lv_obj_t * ui_lessvbatttoohighname;
extern void ui_event_morevbatttoohigh(lv_event_t * e);
extern lv_obj_t * ui_morevbatttoohigh;
extern lv_obj_t * ui_morevbatttoohighname;
extern lv_obj_t * ui_vbatthighname;
extern lv_obj_t * ui_vbatthighvalue;
extern void ui_event_lessvbatthigh(lv_event_t * e);
extern lv_obj_t * ui_lessvbatthigh;
extern lv_obj_t * ui_lessvbatthighname;
extern void ui_event_morevbatthigh(lv_event_t * e);
extern lv_obj_t * ui_morevbatthigh;
extern lv_obj_t * ui_morevbatthighname;
extern lv_obj_t * ui_vbattlowname;
extern lv_obj_t * ui_vbattlowvalue;
extern void ui_event_lessvbattlow(lv_event_t * e);
extern lv_obj_t * ui_lessvbattlow;
extern lv_obj_t * ui_lessvbattlowname;
extern void ui_event_morevbattlow(lv_event_t * e);
extern lv_obj_t * ui_morevbattlow;
extern lv_obj_t * ui_morevbattlowname;
extern lv_obj_t * ui_settingswatert;
extern lv_obj_t * ui_waterhotname;
extern lv_obj_t * ui_waterhotvalue;
extern void ui_event_lessrwaterhot(lv_event_t * e);
extern lv_obj_t * ui_lessrwaterhot;
extern lv_obj_t * ui_lessrwaterhotname;
extern void ui_event_morerwaterhot(lv_event_t * e);
extern lv_obj_t * ui_morerwaterhot;
extern lv_obj_t * ui_morerwaterhotname;
extern lv_obj_t * ui_watermidname;
extern lv_obj_t * ui_watermidvalue;
extern void ui_event_lesswatermid(lv_event_t * e);
extern lv_obj_t * ui_lesswatermid;
extern lv_obj_t * ui_lesswatermidname;
extern void ui_event_morewatermid(lv_event_t * e);
extern lv_obj_t * ui_morewatermid;
extern lv_obj_t * ui_morewatermid1;
extern lv_obj_t * ui_watercoldname;
extern lv_obj_t * ui_watercoldvalue;
extern void ui_event_lesswatercold(lv_event_t * e);
extern lv_obj_t * ui_lesswatercold;
extern lv_obj_t * ui_lesswatercoldname;
extern void ui_event_morewatercold(lv_event_t * e);
extern lv_obj_t * ui_morewatercold;
extern lv_obj_t * ui_morewatercoldname;
extern lv_obj_t * ui_settingsoilt;
extern lv_obj_t * ui_oilhotname;
extern lv_obj_t * ui_oilhotvalue;
extern void ui_event_lessoilhot(lv_event_t * e);
extern lv_obj_t * ui_lessoilhot;
extern lv_obj_t * ui_lessoilhotname;
extern void ui_event_moreoilhot(lv_event_t * e);
extern lv_obj_t * ui_moreoilhot;
extern lv_obj_t * ui_moreoilhotname;
extern lv_obj_t * ui_oilmildname;
extern lv_obj_t * ui_oilmildvalue;
extern void ui_event_lessoilmild(lv_event_t * e);
extern lv_obj_t * ui_lessoilmild;
extern lv_obj_t * ui_lessoilmildname;
extern void ui_event_moreoilmild(lv_event_t * e);
extern lv_obj_t * ui_moreoilmild;
extern lv_obj_t * ui_moreoilmildname;
extern lv_obj_t * ui_oilcoldname;
extern lv_obj_t * ui_oilcoldvalue;
extern void ui_event_lessoilcold(lv_event_t * e);
extern lv_obj_t * ui_lessoilcold;
extern lv_obj_t * ui_lessoilcoldname;
extern void ui_event_moreoilcold(lv_event_t * e);
extern lv_obj_t * ui_moreoilcold;
extern lv_obj_t * ui_moreoilcoldname;
extern lv_obj_t * ui_settingsoilp;
extern lv_obj_t * ui_oilptoohighname;
extern lv_obj_t * ui_oilptoohighvalue;
extern void ui_event_lessoilptoohigh(lv_event_t * e);
extern lv_obj_t * ui_lessoilptoohigh;
extern lv_obj_t * ui_lessoilptoohighname;
extern void ui_event_moreoilptoohigh(lv_event_t * e);
extern lv_obj_t * ui_moreoilptoohigh;
extern lv_obj_t * ui_moreoilptoohighname;
extern lv_obj_t * ui_oilphighname;
extern lv_obj_t * ui_oilphighvalue;
extern void ui_event_lessoilphigh(lv_event_t * e);
extern lv_obj_t * ui_lessoilphigh;
extern lv_obj_t * ui_lessoilphighname;
extern void ui_event_moreoilphigh(lv_event_t * e);
extern lv_obj_t * ui_moreoilphigh;
extern lv_obj_t * ui_moreoilphighname;
extern lv_obj_t * ui_oilplowname;
extern lv_obj_t * ui_oilplowvalue;
extern void ui_event_lessoilplow(lv_event_t * e);
extern lv_obj_t * ui_lessoilplow;
extern lv_obj_t * ui_lessoilplowname;
extern void ui_event_moreoilplow(lv_event_t * e);
extern lv_obj_t * ui_moreoilplow;
extern lv_obj_t * ui_moreoilploname;
extern lv_obj_t * ui_settingsfuelp;
extern lv_obj_t * ui_fuelptoohighname;
extern lv_obj_t * ui_fuelptoohighvalue;
extern void ui_event_lessfuelptoohigh(lv_event_t * e);
extern lv_obj_t * ui_lessfuelptoohigh;
extern lv_obj_t * ui_lessfuelptoohighname;
extern void ui_event_morefuelptoohigh(lv_event_t * e);
extern lv_obj_t * ui_morefuelptoohigh;
extern lv_obj_t * ui_morefuelptoohighname;
extern lv_obj_t * ui_fuelphighname;
extern lv_obj_t * ui_fuelphighvalue;
extern void ui_event_lessfuelphigh(lv_event_t * e);
extern lv_obj_t * ui_lessfuelphigh;
extern lv_obj_t * ui_lessfuelphighname;
extern void ui_event_morefuelphigh(lv_event_t * e);
extern lv_obj_t * ui_morefuelphigh;
extern lv_obj_t * ui_morefuelphighname;
extern lv_obj_t * ui_fuelplowname;
extern lv_obj_t * ui_fuelplowvalue;
extern void ui_event_lessfuelplow(lv_event_t * e);
extern lv_obj_t * ui_lessfuelplow;
extern lv_obj_t * ui_lessfuelplowname;
extern void ui_event_morefuelplow(lv_event_t * e);
extern lv_obj_t * ui_morefuelplow;
extern lv_obj_t * ui_morefuelplowname;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

