// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_FONDO 0
#define UI_THEME_COLOR_TEXTO 1
#define UI_THEME_COLOR_FBARRA 2
#define UI_THEME_COLOR_BARRAR 3

#define UI_THEME_DEFAULT 0

#define UI_THEME_OSCURO 1

#define UI_THEME_CLARO 2

extern const ui_theme_variable_t _ui_theme_color_fondo[3];
extern const ui_theme_variable_t _ui_theme_alpha_fondo[3];

extern const ui_theme_variable_t _ui_theme_color_texto[3];
extern const ui_theme_variable_t _ui_theme_alpha_texto[3];

extern const ui_theme_variable_t _ui_theme_color_fbarra[3];
extern const ui_theme_variable_t _ui_theme_alpha_fbarra[3];

extern const ui_theme_variable_t _ui_theme_color_barrar[3];
extern const ui_theme_variable_t _ui_theme_alpha_barrar[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
