// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#include "../../include/ui/ui.h"

lv_obj_t * ui_bootscreen = NULL;
lv_obj_t * ui_logoboot = NULL;
// event funtions

// build funtions

void ui_bootscreen_screen_init(void)
{
    ui_bootscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_bootscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_bootscreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_bootscreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);

    ui_logoboot = lv_img_create(ui_bootscreen);
    lv_img_set_src(ui_logoboot, &ui_img_logo_volante_png);
    lv_obj_set_width(ui_logoboot, LV_SIZE_CONTENT);   /// 660
    lv_obj_set_height(ui_logoboot, LV_SIZE_CONTENT);    /// 161
    lv_obj_set_align(ui_logoboot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logoboot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logoboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_bootscreen_screen_destroy(void)
{
    if(ui_bootscreen) lv_obj_del(ui_bootscreen);

    // NULL screen variables
    ui_bootscreen = NULL;
    ui_logoboot = NULL;

}
