// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26

#include "../../include/ui/ui.h"
#include "../../include/ajustes.hpp"
#include "../../include/crowpanel_controller.hpp"
#include "../../include/data_processor.hpp"
#include "../../include/can.hpp"

extern CAN canController;

static int rpm=8000;
static int desp=0;
static bool modo_oscuro=true;
static int pantalla=0;
static int rpm_display=0;
static int diff_rpm=1200;
static int recepcion_datos=0;

static float vbatt_too_high=15.0;
static float vbatt_high=14.5;
static float vbatt_low=12.5;

static int water_hot=110;
static int water_mild=100;
static int water_cold=70;

static int oil_hot=110;
static int oil_mild=100;
static int oil_cold=70;

static float oil_pressure_too_high=4.0;
static float oil_pressure_high=3.0;
static float oil_pressure_low=1.0;

static float fuel_pressure_too_high=15.0;
static float fuel_pressure_high=12.0;
static float fuel_pressure_low=3.0;

void refresh_ui_values();

void set(){
    rpm=get_rpm();
    desp=get_desplazamiento();
    modo_oscuro=get_modo_oscuro();
    pantalla=get_pantalla();
    rpm_display=get_rpm_display();
    diff_rpm=get_diff_rpm();
    recepcion_datos=get_recepcion_datos();

    vbatt_too_high=get_vbatt_too_high();
    vbatt_high=get_vbatt_high();
    vbatt_low=get_vbatt_low();

    water_hot=get_water_hot();
    water_mild=get_water_mild();
    water_cold=get_water_cold();

    oil_hot=get_oil_hot();
    oil_mild=get_oil_mild();
    oil_cold=get_oil_cold();

    oil_pressure_too_high=get_oil_pressure_too_high();
    oil_pressure_high=get_oil_pressure_high();
    oil_pressure_low=get_oil_pressure_low();

    fuel_pressure_too_high=get_fuel_pressure_too_high();
    fuel_pressure_high=get_fuel_pressure_high();
    fuel_pressure_low=get_fuel_pressure_low();
}

void update_all(){
    update(
        rpm,
        desp,
        modo_oscuro,
        pantalla,
        rpm_display,
        diff_rpm,
        recepcion_datos,
        vbatt_too_high,
        vbatt_high,
        vbatt_low,
        water_hot,
        water_mild,
        water_cold,
        oil_hot,
        oil_mild,
        oil_cold,
        oil_pressure_too_high,
        oil_pressure_high,
        oil_pressure_low,
        fuel_pressure_too_high,
        fuel_pressure_high,
        fuel_pressure_low
    );
}

void abrirajustes(lv_event_t * e)
{
    set();
    refresh_ui_values();
}

void cerrarajustes(lv_event_t * e)
{
    set();
    save();
    DataProcessor::set_dataprocessor();
    CrowPanelController::create_rpm_bar(((rpm/1000)*1000), desp);
    lv_scr_load(ui_Screen1);
}

void opcionesdrop(lv_event_t * e)
{
    lv_obj_t * obj=lv_event_get_target(e);
    int opcion=lv_dropdown_get_selected(obj);

    lv_obj_add_flag(ui_settingsmain, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsrpm, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsvbatt, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingswatert, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsoilt, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsoilp, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsfuelp, LV_OBJ_FLAG_HIDDEN);

    switch(opcion){
        case 0:
            lv_obj_clear_flag(ui_settingsmain, LV_OBJ_FLAG_HIDDEN);
            break;

        case 1:
            lv_obj_clear_flag(ui_settingsrpm, LV_OBJ_FLAG_HIDDEN);
            break;

        case 2:
            lv_obj_clear_flag(ui_settingsvbatt, LV_OBJ_FLAG_HIDDEN);
            break;

        case 3:
            lv_obj_clear_flag(ui_settingswatert, LV_OBJ_FLAG_HIDDEN);
            break;

        case 4:
            lv_obj_clear_flag(ui_settingsoilt, LV_OBJ_FLAG_HIDDEN);
            break;

        case 5:
            lv_obj_clear_flag(ui_settingsoilp, LV_OBJ_FLAG_HIDDEN);
            break;

        case 6:
            lv_obj_clear_flag(ui_settingsfuelp, LV_OBJ_FLAG_HIDDEN);
            break;
    }
}

void themesitch(lv_event_t * e)
{
    set();

    lv_obj_t * obj=lv_event_get_target(e);

    if(lv_obj_has_state(obj, LV_STATE_CHECKED)){
        modo_oscuro=true;
        ui_theme_set(1);
    } else {
        modo_oscuro=false;
        ui_theme_set(2);
    }

    update_all();
}

void cambiarpantalla(lv_event_t * e)
{
    set();

    lv_obj_t * obj=lv_event_get_target(e);

    pantalla=0;
    if(lv_dropdown_get_selected(obj)==0){
        lv_scr_load(ui_Screen1);
    } else {
        lv_scr_load(ui_Screen2);
    }

    update_all();
}

void cambiardatos(lv_event_t * e)
{
    lv_obj_t * obj=lv_event_get_target(e);
    recepcion_datos=lv_dropdown_get_selected(obj);

    if(recepcion_datos==0){
        canController.stop_iracing_task();
        canController.clear_rx_queue();
        canController.start_listening_task();
    } else {
        canController.stop_listening_task();
        canController.start_iracing_task();
    }

    update_all();
    save();
}

void lessrpm_(lv_event_t * e)
{
    set();

    if(rpm<=5000){
        return;
    } else {
        rpm=modify_value(rpm, -50);
    }

    CrowPanelController::set_value_to_label(ui_rpmfinalvalue, rpm);

    update_all();
}

void morerpm_(lv_event_t * e)
{
    set();

    if(rpm>=14000){
        return;
    } else {
        rpm=modify_value(rpm, 50);
    }

    CrowPanelController::set_value_to_label(ui_rpmfinalvalue, rpm);

    update_all();
}

void lessdesp(lv_event_t * e)
{
    set();

    if(desp<=-45){
        return;
    } else {
        desp=modify_value(desp, -1);
    }

    CrowPanelController::set_value_to_label(ui_desplazamientovalue, desp);

    update_all();
}

void moredesp(lv_event_t * e)
{
    set();

    if(desp>=15){
        return;
    } else {
        desp=modify_value(desp, 1);
    }

    CrowPanelController::set_value_to_label(ui_desplazamientovalue, desp);

    update_all();
}

void rpmdisplay(lv_event_t * e)
{
    set();

    lv_obj_t * obj=lv_event_get_target(e);

    lv_obj_add_flag(ui_barcontainer, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tiraledsrpmcontainer, LV_OBJ_FLAG_HIDDEN);

    if(lv_dropdown_get_selected(obj)==0){
        lv_obj_clear_flag(ui_barcontainer, LV_OBJ_FLAG_HIDDEN);
        rpm_display=0;   // Barra
    } else if (lv_dropdown_get_selected(obj)==1) {
        lv_obj_clear_flag(ui_tiraledsrpmcontainer, LV_OBJ_FLAG_HIDDEN);
        rpm_display=1;  // Leds
    } else if (lv_dropdown_get_selected(obj)==2){
        lv_obj_clear_flag(ui_barcontainer, LV_OBJ_FLAG_HIDDEN);
        rpm_display=2;   // Barra lineal
    } else {
        lv_obj_clear_flag(ui_tiraledsrpmcontainer, LV_OBJ_FLAG_HIDDEN);
        rpm_display=3;  // Leds lineal
    }

    update_all();
}

void lessdiffrpm(lv_event_t * e)
{
    set();

    if(diff_rpm<=0){
        return;
    } else {
        diff_rpm=modify_value(diff_rpm, -100);
    }

    CrowPanelController::set_value_to_label(ui_diffrpmvalue, diff_rpm);

    update_all();
}

void morediffrpm(lv_event_t * e)
{
    set();

    diff_rpm=modify_value(diff_rpm, 100);

    CrowPanelController::set_value_to_label(ui_diffrpmvalue, diff_rpm);

    update_all();
}

void lessvbatttoohigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(vbatt_too_high, -0.1f);

    if(nuevo<=vbatt_high){
        return;
    } else {
        vbatt_too_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_vbatttoohighvalue, vbatt_too_high);

    update_all();
}

void morevbatttoohigh(lv_event_t * e)
{
    set();

    vbatt_too_high=modify_value(vbatt_too_high, 0.1f);

    CrowPanelController::set_value_to_label(ui_vbatttoohighvalue, vbatt_too_high);

    update_all();
}

void lessvbatthigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(vbatt_high, -0.1f);

    if(nuevo<=vbatt_low){
        return;
    } else {
        vbatt_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_vbatthighvalue, vbatt_high);

    update_all();
}

void morebvbatthigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(vbatt_high, 0.1f);

    if(nuevo>=vbatt_too_high){
        return;
    } else {
        vbatt_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_vbatthighvalue, vbatt_high);

    update_all();
}

void lessvbattlow(lv_event_t * e)
{
    set();

    if(vbatt_low<=0){
        return;
    } else {
        vbatt_low=modify_value(vbatt_low, -0.1f);
    }

    CrowPanelController::set_value_to_label(ui_vbattlowvalue, vbatt_low);

    update_all();
}

void morevbattlow(lv_event_t * e)
{
    set();

    float nuevo=modify_value(vbatt_low, 0.1f);

    if(nuevo>=vbatt_high){
        return;
    } else {
        vbatt_low=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_vbattlowvalue, vbatt_low);

    update_all();
}

void lesswaterhot(lv_event_t * e)
{
    set();

    int nuevo=modify_value(water_hot, -1);

    if(nuevo<=water_mild){
        return;
    } else {
        water_hot=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_waterhotvalue, water_hot);

    update_all();
}

void mroewaterhot(lv_event_t * e)
{
    set();

    water_hot=modify_value(water_hot, 1);

    CrowPanelController::set_value_to_label(ui_waterhotvalue, water_hot);

    update_all();
}

void lesswatermild(lv_event_t * e)
{
    set();

    int nuevo=modify_value(water_mild, -1);

    if(nuevo<=water_cold){
        return;
    } else {
        water_mild=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_watermidvalue, water_mild);

    update_all();
}

void morewatermild(lv_event_t * e)
{
    set();

    int nuevo=modify_value(water_mild, 1);

    if(nuevo>=water_hot){
        return;
    } else {
        water_mild=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_watermidvalue, water_mild);

    update_all();
}

void lesswatercold(lv_event_t * e)
{
    set();

    if(water_cold<=0){
        return;
    } else {
        water_cold=modify_value(water_cold, -1);
    }

    CrowPanelController::set_value_to_label(ui_watercoldvalue, water_cold);

    update_all();
}

void morewatercold(lv_event_t * e)
{
    set();

    int nuevo=modify_value(water_cold, 1);

    if(nuevo>=water_mild){
        return;
    } else {
        water_cold=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_watercoldvalue, water_cold);

    update_all();
}

void lessoilhot(lv_event_t * e)
{
    set();

    int nuevo=modify_value(oil_hot, -1);

    if(nuevo<=oil_mild){
        return;
    } else {
        oil_hot=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_oilhotvalue, oil_hot);

    update_all();
}

void moreoilhot(lv_event_t * e)
{
    set();

    oil_hot=modify_value(oil_hot, 1);

    CrowPanelController::set_value_to_label(ui_oilhotvalue, oil_hot);

    update_all();
}

void lessoilmild(lv_event_t * e)
{
    set();

    int nuevo=modify_value(oil_mild, -1);

    if(nuevo<=oil_cold){
        return;
    } else {
        oil_mild=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_oilmildvalue, oil_mild);

    update_all();
}

void moreoilmild(lv_event_t * e)
{
    set();

    int nuevo=modify_value(oil_mild, 1);

    if(nuevo>=oil_hot){
        return;
    } else {
        oil_mild=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_oilmildvalue, oil_mild);

    update_all();
}

void lessoilcold(lv_event_t * e)
{
    set();

    if(oil_cold<=0){
        return;
    } else {
        oil_cold=modify_value(oil_cold, -1);
    }

    CrowPanelController::set_value_to_label(ui_oilcoldvalue, oil_cold);

    update_all();
}

void moreoilcold(lv_event_t * e)
{
    set();

    int nuevo=modify_value(oil_cold, 1);

    if(nuevo>=oil_mild){
        return;
    } else {
        oil_cold=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_oilcoldvalue, oil_cold);

    update_all();
}

void lessoilptoohigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(oil_pressure_too_high, -0.1f);

    if(nuevo<=oil_pressure_high){
        return;
    } else {
        oil_pressure_too_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_oilptoohighvalue, oil_pressure_too_high);

    update_all();
}

void moreoilptoohigh(lv_event_t * e)
{
    set();

    oil_pressure_too_high=modify_value(oil_pressure_too_high, 0.1f);

    CrowPanelController::set_value_to_label(ui_oilptoohighvalue, oil_pressure_too_high);

    update_all();
}

void lessoilphigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(oil_pressure_high, -0.1f);

    if(nuevo<=oil_pressure_low){
        return;
    } else {
        oil_pressure_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_oilphighvalue, oil_pressure_high);

    update_all();
}

void moreoilphigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(oil_pressure_high, 0.1f);

    if(nuevo>=oil_pressure_too_high){
        return;
    } else {
        oil_pressure_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_oilphighvalue, oil_pressure_high);

    update_all();
}

void lessoilplow(lv_event_t * e)
{
    set();

    if(oil_pressure_low<=0){
        return;
    } else {
        oil_pressure_low=modify_value(oil_pressure_low, -0.1f);
    }

    CrowPanelController::set_value_to_label(ui_oilplowvalue, oil_pressure_low);

    update_all();
}

void moreoilplow(lv_event_t * e)
{
    set();

    float nuevo=modify_value(oil_pressure_low, 0.1f);

    if(nuevo>=oil_pressure_high){
        return;
    } else {
        oil_pressure_low=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_oilplowvalue, oil_pressure_low);

    update_all();
}

void lessfuelptoohigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(fuel_pressure_too_high, -0.1f);

    if(nuevo<=fuel_pressure_high){
        return;
    } else {
        fuel_pressure_too_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_fuelptoohighvalue, fuel_pressure_too_high);

    update_all();
}

void morefuelptoohigh(lv_event_t * e)
{
    set();

    fuel_pressure_too_high=modify_value(fuel_pressure_too_high, 0.1f);

    CrowPanelController::set_value_to_label(ui_fuelptoohighvalue, fuel_pressure_too_high);

    update_all();
}

void lessfuelphigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(fuel_pressure_high, -0.1f);

    if(nuevo<=fuel_pressure_low){
        return;
    } else {
        fuel_pressure_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_fuelphighvalue, fuel_pressure_high);

    update_all();
}

void morefuelphigh(lv_event_t * e)
{
    set();

    float nuevo=modify_value(fuel_pressure_high, 0.1f);

    if(nuevo>=fuel_pressure_too_high){
        return;
    } else {
        fuel_pressure_high=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_fuelphighvalue, fuel_pressure_high);

    update_all();
}

void lessfuelp(lv_event_t * e)
{
    set();

    if(fuel_pressure_low<=0){
        return;
    } else {
        fuel_pressure_low=modify_value(fuel_pressure_low, -0.1f);
    }

    CrowPanelController::set_value_to_label(ui_fuelplowvalue, fuel_pressure_low);

    update_all();
}

void morefuelplow(lv_event_t * e)
{
    set();

    float nuevo=modify_value(fuel_pressure_low, 0.1f);

    if(nuevo>=fuel_pressure_high){
        return;
    } else {
        fuel_pressure_low=nuevo;
    }

    CrowPanelController::set_value_to_label(ui_fuelplowvalue, fuel_pressure_low);

    update_all();
}

void refresh_ui_values(){

    CrowPanelController::set_value_to_label(ui_rpmfinalvalue, rpm);
    CrowPanelController::set_value_to_label(ui_desplazamientovalue, desp);
    CrowPanelController::set_value_to_label(ui_diffrpmvalue, diff_rpm);

    CrowPanelController::set_value_to_label(ui_vbatttoohighvalue, vbatt_too_high);
    CrowPanelController::set_value_to_label(ui_vbatthighvalue, vbatt_high);
    CrowPanelController::set_value_to_label(ui_vbattlowvalue, vbatt_low);

    CrowPanelController::set_value_to_label(ui_waterhotvalue, water_hot);
    CrowPanelController::set_value_to_label(ui_watermidvalue, water_mild);
    CrowPanelController::set_value_to_label(ui_watercoldvalue, water_cold);

    CrowPanelController::set_value_to_label(ui_oilhotvalue, oil_hot);
    CrowPanelController::set_value_to_label(ui_oilmildvalue, oil_mild);
    CrowPanelController::set_value_to_label(ui_oilcoldvalue, oil_cold);

    CrowPanelController::set_value_to_label(ui_oilptoohighvalue, oil_pressure_too_high);
    CrowPanelController::set_value_to_label(ui_oilphighvalue, oil_pressure_high);
    CrowPanelController::set_value_to_label(ui_oilplowvalue, oil_pressure_low);

    CrowPanelController::set_value_to_label(ui_fuelptoohighvalue, fuel_pressure_too_high);
    CrowPanelController::set_value_to_label(ui_fuelphighvalue, fuel_pressure_high);
    CrowPanelController::set_value_to_label(ui_fuelplowvalue, fuel_pressure_low);

    if(modo_oscuro){
        lv_obj_add_state(ui_modooscuoswitch, LV_STATE_CHECKED);
    } else {
        lv_obj_clear_state(ui_modooscuoswitch, LV_STATE_CHECKED);
    }

    lv_dropdown_set_selected(ui_pantalladrop, pantalla);
    lv_dropdown_set_selected(ui_rpmdisplaydrop, rpm_display);
    lv_dropdown_set_selected(ui_recepciondatosdrop, recepcion_datos);

    lv_dropdown_set_selected(ui_opciondrop, 0);
    lv_obj_clear_flag(ui_settingsmain, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsrpm, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsvbatt, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingswatert, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsoilt, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsoilp, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_settingsfuelp, LV_OBJ_FLAG_HIDDEN);
}