// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#include "../../include/ui/ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_aux1panel = NULL;
lv_obj_t * ui_aux1name = NULL;
lv_obj_t * ui_aux1 = NULL;
lv_obj_t * ui_aux1separator = NULL;
lv_obj_t * ui_aux3panel = NULL;
lv_obj_t * ui_aux3name = NULL;
lv_obj_t * ui_aux3 = NULL;
lv_obj_t * ui_aux3separator = NULL;
lv_obj_t * ui_aux4panel = NULL;
lv_obj_t * ui_aux4name = NULL;
lv_obj_t * ui_aux4 = NULL;
lv_obj_t * ui_aux4separator = NULL;
lv_obj_t * ui_aux5panel = NULL;
lv_obj_t * ui_aux5name = NULL;
lv_obj_t * ui_aux5 = NULL;
lv_obj_t * ui_aux5separator = NULL;
lv_obj_t * ui_aux6panel = NULL;
lv_obj_t * ui_aux6name = NULL;
lv_obj_t * ui_aux6 = NULL;
lv_obj_t * ui_aux6separator = NULL;
lv_obj_t * ui_aux7panel = NULL;
lv_obj_t * ui_aux7name = NULL;
lv_obj_t * ui_aux7 = NULL;
lv_obj_t * ui_aux7separator = NULL;
lv_obj_t * ui_aux8panel = NULL;
lv_obj_t * ui_aux8name = NULL;
lv_obj_t * ui_aux8 = NULL;
lv_obj_t * ui_aux8separator = NULL;
lv_obj_t * ui_dig1panel = NULL;
lv_obj_t * ui_dig1name = NULL;
lv_obj_t * ui_dig1 = NULL;
lv_obj_t * ui_dig1separator = NULL;
lv_obj_t * ui_throttlepanel = NULL;
lv_obj_t * ui_throttlename = NULL;
lv_obj_t * ui_throttle = NULL;
lv_obj_t * ui_throttleseparator = NULL;
lv_obj_t * ui_nousepanel = NULL;
lv_obj_t * ui_nousename = NULL;
lv_obj_t * ui_nouse = NULL;
lv_obj_t * ui_nouseseparator = NULL;
lv_obj_t * ui_lambdtrgapanel = NULL;
lv_obj_t * ui_lambdatrgname = NULL;
lv_obj_t * ui_lambdatrg = NULL;
lv_obj_t * ui_lambdatrgseparator = NULL;
lv_obj_t * ui_mappanel = NULL;
lv_obj_t * ui_mapname = NULL;
lv_obj_t * ui_map = NULL;
lv_obj_t * ui_mapseparator = NULL;
lv_obj_t * ui_brakepanel = NULL;
lv_obj_t * ui_brakename = NULL;
lv_obj_t * ui_brake = NULL;
lv_obj_t * ui_brakeseparator = NULL;
lv_obj_t * ui_botonshowajustes2 = NULL;
lv_obj_t * ui_ajustesboton2 = NULL;
lv_obj_t * ui_ajustesnombre2 = NULL;
// event funtions
void ui_event_botonshowajustes2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_ajustesboton2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ajustesboton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingscreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settingscreen_screen_init);
        _ui_flag_modify(ui_ajustesboton2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        abrirajustes(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_Screen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);

    ui_aux1panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_aux1panel, 125);
    lv_obj_set_height(ui_aux1panel, 100);
    lv_obj_set_x(ui_aux1panel, 160);
    lv_obj_set_y(ui_aux1panel, -144);
    lv_obj_set_align(ui_aux1panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux1panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux1panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux1panel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux1panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux1panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux1panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux1name = lv_label_create(ui_aux1panel);
    lv_obj_set_width(ui_aux1name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux1name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux1name, 0);
    lv_obj_set_y(ui_aux1name, -30);
    lv_obj_set_align(ui_aux1name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux1name, "AUX 1");
    ui_object_set_themeable_style_property(ui_aux1name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux1name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux1name, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux1 = lv_label_create(ui_aux1panel);
    lv_obj_set_width(ui_aux1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux1, 0);
    lv_obj_set_y(ui_aux1, 17);
    lv_obj_set_align(ui_aux1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux1, "OFF");
    ui_object_set_themeable_style_property(ui_aux1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux1, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux1separator = lv_obj_create(ui_aux1panel);
    lv_obj_set_width(ui_aux1separator, 70);
    lv_obj_set_height(ui_aux1separator, 1);
    lv_obj_set_x(ui_aux1separator, 0);
    lv_obj_set_y(ui_aux1separator, -14);
    lv_obj_set_align(ui_aux1separator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux1separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux1separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux1separator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux1separator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux1separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux1separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux3panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_aux3panel, 125);
    lv_obj_set_height(ui_aux3panel, 100);
    lv_obj_set_x(ui_aux3panel, 283);
    lv_obj_set_y(ui_aux3panel, -144);
    lv_obj_set_align(ui_aux3panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux3panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux3panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux3panel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux3panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux3panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux3panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux3name = lv_label_create(ui_aux3panel);
    lv_obj_set_width(ui_aux3name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux3name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux3name, 0);
    lv_obj_set_y(ui_aux3name, -30);
    lv_obj_set_align(ui_aux3name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux3name, "AUX 3");
    ui_object_set_themeable_style_property(ui_aux3name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux3name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux3name, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux3 = lv_label_create(ui_aux3panel);
    lv_obj_set_width(ui_aux3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux3, 0);
    lv_obj_set_y(ui_aux3, 17);
    lv_obj_set_align(ui_aux3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux3, "OFF");
    ui_object_set_themeable_style_property(ui_aux3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux3, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux3separator = lv_obj_create(ui_aux3panel);
    lv_obj_set_width(ui_aux3separator, 70);
    lv_obj_set_height(ui_aux3separator, 1);
    lv_obj_set_x(ui_aux3separator, 0);
    lv_obj_set_y(ui_aux3separator, -14);
    lv_obj_set_align(ui_aux3separator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux3separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux3separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux3separator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux3separator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux3separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux3separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux4panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_aux4panel, 125);
    lv_obj_set_height(ui_aux4panel, 100);
    lv_obj_set_x(ui_aux4panel, 160);
    lv_obj_set_y(ui_aux4panel, -46);
    lv_obj_set_align(ui_aux4panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux4panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux4panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux4panel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux4panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux4panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux4panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux4name = lv_label_create(ui_aux4panel);
    lv_obj_set_width(ui_aux4name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux4name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux4name, 0);
    lv_obj_set_y(ui_aux4name, -30);
    lv_obj_set_align(ui_aux4name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux4name, "AUX 4");
    ui_object_set_themeable_style_property(ui_aux4name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux4name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux4name, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux4 = lv_label_create(ui_aux4panel);
    lv_obj_set_width(ui_aux4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux4, 0);
    lv_obj_set_y(ui_aux4, 17);
    lv_obj_set_align(ui_aux4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux4, "OFF");
    ui_object_set_themeable_style_property(ui_aux4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux4, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux4separator = lv_obj_create(ui_aux4panel);
    lv_obj_set_width(ui_aux4separator, 70);
    lv_obj_set_height(ui_aux4separator, 1);
    lv_obj_set_x(ui_aux4separator, 0);
    lv_obj_set_y(ui_aux4separator, -14);
    lv_obj_set_align(ui_aux4separator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux4separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux4separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux4separator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux4separator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux4separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux4separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux5panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_aux5panel, 125);
    lv_obj_set_height(ui_aux5panel, 100);
    lv_obj_set_x(ui_aux5panel, 283);
    lv_obj_set_y(ui_aux5panel, -46);
    lv_obj_set_align(ui_aux5panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux5panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux5panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux5panel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux5panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux5panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux5panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux5name = lv_label_create(ui_aux5panel);
    lv_obj_set_width(ui_aux5name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux5name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux5name, 0);
    lv_obj_set_y(ui_aux5name, -30);
    lv_obj_set_align(ui_aux5name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux5name, "AUX 5");
    ui_object_set_themeable_style_property(ui_aux5name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux5name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux5name, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux5 = lv_label_create(ui_aux5panel);
    lv_obj_set_width(ui_aux5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux5, 0);
    lv_obj_set_y(ui_aux5, 17);
    lv_obj_set_align(ui_aux5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux5, "OFF");
    ui_object_set_themeable_style_property(ui_aux5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux5, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux5separator = lv_obj_create(ui_aux5panel);
    lv_obj_set_width(ui_aux5separator, 70);
    lv_obj_set_height(ui_aux5separator, 1);
    lv_obj_set_x(ui_aux5separator, 0);
    lv_obj_set_y(ui_aux5separator, -14);
    lv_obj_set_align(ui_aux5separator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux5separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux5separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux5separator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux5separator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux5separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux5separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux6panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_aux6panel, 125);
    lv_obj_set_height(ui_aux6panel, 100);
    lv_obj_set_x(ui_aux6panel, 160);
    lv_obj_set_y(ui_aux6panel, 51);
    lv_obj_set_align(ui_aux6panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux6panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux6panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux6panel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux6panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux6panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux6panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux6name = lv_label_create(ui_aux6panel);
    lv_obj_set_width(ui_aux6name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux6name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux6name, 0);
    lv_obj_set_y(ui_aux6name, -30);
    lv_obj_set_align(ui_aux6name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux6name, "AUX 6");
    ui_object_set_themeable_style_property(ui_aux6name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux6name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux6name, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux6 = lv_label_create(ui_aux6panel);
    lv_obj_set_width(ui_aux6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux6, 0);
    lv_obj_set_y(ui_aux6, 17);
    lv_obj_set_align(ui_aux6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux6, "OFF");
    ui_object_set_themeable_style_property(ui_aux6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux6, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux6separator = lv_obj_create(ui_aux6panel);
    lv_obj_set_width(ui_aux6separator, 70);
    lv_obj_set_height(ui_aux6separator, 1);
    lv_obj_set_x(ui_aux6separator, 0);
    lv_obj_set_y(ui_aux6separator, -14);
    lv_obj_set_align(ui_aux6separator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux6separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux6separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux6separator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux6separator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux6separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux6separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux7panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_aux7panel, 125);
    lv_obj_set_height(ui_aux7panel, 100);
    lv_obj_set_x(ui_aux7panel, 283);
    lv_obj_set_y(ui_aux7panel, 51);
    lv_obj_set_align(ui_aux7panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux7panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux7panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux7panel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux7panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux7panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux7panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux7name = lv_label_create(ui_aux7panel);
    lv_obj_set_width(ui_aux7name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux7name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux7name, 0);
    lv_obj_set_y(ui_aux7name, -30);
    lv_obj_set_align(ui_aux7name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux7name, "AUX 7");
    ui_object_set_themeable_style_property(ui_aux7name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux7name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux7name, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux7 = lv_label_create(ui_aux7panel);
    lv_obj_set_width(ui_aux7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux7, 0);
    lv_obj_set_y(ui_aux7, 17);
    lv_obj_set_align(ui_aux7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux7, "OFF");
    ui_object_set_themeable_style_property(ui_aux7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux7, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux7separator = lv_obj_create(ui_aux7panel);
    lv_obj_set_width(ui_aux7separator, 70);
    lv_obj_set_height(ui_aux7separator, 1);
    lv_obj_set_x(ui_aux7separator, 0);
    lv_obj_set_y(ui_aux7separator, -14);
    lv_obj_set_align(ui_aux7separator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux7separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux7separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux7separator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux7separator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux7separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux7separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux8panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_aux8panel, 125);
    lv_obj_set_height(ui_aux8panel, 100);
    lv_obj_set_x(ui_aux8panel, 160);
    lv_obj_set_y(ui_aux8panel, 149);
    lv_obj_set_align(ui_aux8panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux8panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux8panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux8panel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux8panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux8panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux8panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_aux8name = lv_label_create(ui_aux8panel);
    lv_obj_set_width(ui_aux8name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux8name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux8name, 0);
    lv_obj_set_y(ui_aux8name, -30);
    lv_obj_set_align(ui_aux8name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux8name, "AUX 8");
    ui_object_set_themeable_style_property(ui_aux8name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux8name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux8name, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux8 = lv_label_create(ui_aux8panel);
    lv_obj_set_width(ui_aux8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aux8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aux8, 0);
    lv_obj_set_y(ui_aux8, 17);
    lv_obj_set_align(ui_aux8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aux8, "OFF");
    ui_object_set_themeable_style_property(ui_aux8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_aux8, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aux8separator = lv_obj_create(ui_aux8panel);
    lv_obj_set_width(ui_aux8separator, 70);
    lv_obj_set_height(ui_aux8separator, 1);
    lv_obj_set_x(ui_aux8separator, 0);
    lv_obj_set_y(ui_aux8separator, -14);
    lv_obj_set_align(ui_aux8separator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_aux8separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aux8separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aux8separator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aux8separator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aux8separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_aux8separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_dig1panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_dig1panel, 125);
    lv_obj_set_height(ui_dig1panel, 100);
    lv_obj_set_x(ui_dig1panel, 283);
    lv_obj_set_y(ui_dig1panel, 149);
    lv_obj_set_align(ui_dig1panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dig1panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dig1panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dig1panel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dig1panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_dig1panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_dig1panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_dig1name = lv_label_create(ui_dig1panel);
    lv_obj_set_width(ui_dig1name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dig1name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dig1name, 0);
    lv_obj_set_y(ui_dig1name, -30);
    lv_obj_set_align(ui_dig1name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dig1name, "DIG 1");
    ui_object_set_themeable_style_property(ui_dig1name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_dig1name, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_dig1name, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dig1 = lv_label_create(ui_dig1panel);
    lv_obj_set_width(ui_dig1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dig1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dig1, 0);
    lv_obj_set_y(ui_dig1, 17);
    lv_obj_set_align(ui_dig1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dig1, "OFF");
    ui_object_set_themeable_style_property(ui_dig1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_dig1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_dig1, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dig1separator = lv_obj_create(ui_dig1panel);
    lv_obj_set_width(ui_dig1separator, 70);
    lv_obj_set_height(ui_dig1separator, 1);
    lv_obj_set_x(ui_dig1separator, 0);
    lv_obj_set_y(ui_dig1separator, -14);
    lv_obj_set_align(ui_dig1separator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dig1separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dig1separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dig1separator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dig1separator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_dig1separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_dig1separator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_throttlepanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_throttlepanel, 250);
    lv_obj_set_height(ui_throttlepanel, 100);
    lv_obj_set_x(ui_throttlepanel, -240);
    lv_obj_set_y(ui_throttlepanel, -144);
    lv_obj_set_align(ui_throttlepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_throttlepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_throttlepanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_throttlepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_throttlepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_throttlepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_throttlepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_throttlename = lv_label_create(ui_throttlepanel);
    lv_obj_set_width(ui_throttlename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_throttlename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_throttlename, 0);
    lv_obj_set_y(ui_throttlename, -32);
    lv_obj_set_align(ui_throttlename, LV_ALIGN_CENTER);
    lv_label_set_text(ui_throttlename, "THROTTLE");
    ui_object_set_themeable_style_property(ui_throttlename, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_throttlename, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_throttlename, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_throttle = lv_label_create(ui_throttlepanel);
    lv_obj_set_width(ui_throttle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_throttle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_throttle, 0);
    lv_obj_set_y(ui_throttle, 17);
    lv_obj_set_align(ui_throttle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_throttle, "-");
    ui_object_set_themeable_style_property(ui_throttle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_throttle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_throttle, &ui_font_labeld2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_throttleseparator = lv_obj_create(ui_throttlepanel);
    lv_obj_set_width(ui_throttleseparator, 120);
    lv_obj_set_height(ui_throttleseparator, 1);
    lv_obj_set_x(ui_throttleseparator, 2);
    lv_obj_set_y(ui_throttleseparator, -18);
    lv_obj_set_align(ui_throttleseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_throttleseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_throttleseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_throttleseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_throttleseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_nousepanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_nousepanel, 250);
    lv_obj_set_height(ui_nousepanel, 100);
    lv_obj_set_x(ui_nousepanel, -240);
    lv_obj_set_y(ui_nousepanel, -46);
    lv_obj_set_align(ui_nousepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_nousepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_nousepanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_nousepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_nousepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_nousepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_nousepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_nousename = lv_label_create(ui_nousepanel);
    lv_obj_set_width(ui_nousename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nousename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nousename, 0);
    lv_obj_set_y(ui_nousename, -32);
    lv_obj_set_align(ui_nousename, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nousename, "-");
    ui_object_set_themeable_style_property(ui_nousename, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_nousename, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_nousename, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nouse = lv_label_create(ui_nousepanel);
    lv_obj_set_width(ui_nouse, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nouse, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nouse, 0);
    lv_obj_set_y(ui_nouse, 17);
    lv_obj_set_align(ui_nouse, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nouse, "-");
    ui_object_set_themeable_style_property(ui_nouse, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_nouse, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_nouse, &ui_font_labeld2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nouseseparator = lv_obj_create(ui_nousepanel);
    lv_obj_set_width(ui_nouseseparator, 120);
    lv_obj_set_height(ui_nouseseparator, 1);
    lv_obj_set_x(ui_nouseseparator, 2);
    lv_obj_set_y(ui_nouseseparator, -18);
    lv_obj_set_align(ui_nouseseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_nouseseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_nouseseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_nouseseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_nouseseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_lambdtrgapanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_lambdtrgapanel, 250);
    lv_obj_set_height(ui_lambdtrgapanel, 100);
    lv_obj_set_x(ui_lambdtrgapanel, -240);
    lv_obj_set_y(ui_lambdtrgapanel, 52);
    lv_obj_set_align(ui_lambdtrgapanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lambdtrgapanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lambdtrgapanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lambdtrgapanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_lambdtrgapanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_lambdtrgapanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_lambdtrgapanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_lambdatrgname = lv_label_create(ui_lambdtrgapanel);
    lv_obj_set_width(ui_lambdatrgname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lambdatrgname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lambdatrgname, 0);
    lv_obj_set_y(ui_lambdatrgname, -32);
    lv_obj_set_align(ui_lambdatrgname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lambdatrgname, "LAMBDA TARGET");
    ui_object_set_themeable_style_property(ui_lambdatrgname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_lambdatrgname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_lambdatrgname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lambdatrg = lv_label_create(ui_lambdtrgapanel);
    lv_obj_set_width(ui_lambdatrg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lambdatrg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lambdatrg, 0);
    lv_obj_set_y(ui_lambdatrg, 17);
    lv_obj_set_align(ui_lambdatrg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lambdatrg, "-");
    ui_object_set_themeable_style_property(ui_lambdatrg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_lambdatrg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_lambdatrg, &ui_font_labeld2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lambdatrgseparator = lv_obj_create(ui_lambdtrgapanel);
    lv_obj_set_width(ui_lambdatrgseparator, 120);
    lv_obj_set_height(ui_lambdatrgseparator, 1);
    lv_obj_set_x(ui_lambdatrgseparator, 2);
    lv_obj_set_y(ui_lambdatrgseparator, -18);
    lv_obj_set_align(ui_lambdatrgseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lambdatrgseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lambdatrgseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lambdatrgseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_lambdatrgseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_mappanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_mappanel, 218);
    lv_obj_set_height(ui_mappanel, 100);
    lv_obj_set_x(ui_mappanel, -8);
    lv_obj_set_y(ui_mappanel, -144);
    lv_obj_set_align(ui_mappanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mappanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mappanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_mappanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_mappanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_mappanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_mappanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_mapname = lv_label_create(ui_mappanel);
    lv_obj_set_width(ui_mapname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mapname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mapname, 0);
    lv_obj_set_y(ui_mapname, -32);
    lv_obj_set_align(ui_mapname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mapname, "MAP");
    ui_object_set_themeable_style_property(ui_mapname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_mapname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_mapname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_map = lv_label_create(ui_mappanel);
    lv_obj_set_width(ui_map, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_map, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_map, 0);
    lv_obj_set_y(ui_map, 17);
    lv_obj_set_align(ui_map, LV_ALIGN_CENTER);
    lv_label_set_text(ui_map, "-");
    ui_object_set_themeable_style_property(ui_map, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_map, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_map, &ui_font_labeld2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mapseparator = lv_obj_create(ui_mappanel);
    lv_obj_set_width(ui_mapseparator, 120);
    lv_obj_set_height(ui_mapseparator, 1);
    lv_obj_set_x(ui_mapseparator, 2);
    lv_obj_set_y(ui_mapseparator, -18);
    lv_obj_set_align(ui_mapseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mapseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mapseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_mapseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_mapseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_brakepanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_brakepanel, 250);
    lv_obj_set_height(ui_brakepanel, 100);
    lv_obj_set_x(ui_brakepanel, -240);
    lv_obj_set_y(ui_brakepanel, 149);
    lv_obj_set_align(ui_brakepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_brakepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_brakepanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_brakepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_brakepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_brakepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_brakepanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_brakename = lv_label_create(ui_brakepanel);
    lv_obj_set_width(ui_brakename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brakename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brakename, 0);
    lv_obj_set_y(ui_brakename, -32);
    lv_obj_set_align(ui_brakename, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brakename, "BRAKE");
    ui_object_set_themeable_style_property(ui_brakename, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_brakename, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_brakename, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brake = lv_label_create(ui_brakepanel);
    lv_obj_set_width(ui_brake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brake, 0);
    lv_obj_set_y(ui_brake, 17);
    lv_obj_set_align(ui_brake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brake, "-");
    ui_object_set_themeable_style_property(ui_brake, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_brake, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_brake, &ui_font_labeld2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brakeseparator = lv_obj_create(ui_brakepanel);
    lv_obj_set_width(ui_brakeseparator, 120);
    lv_obj_set_height(ui_brakeseparator, 1);
    lv_obj_set_x(ui_brakeseparator, 2);
    lv_obj_set_y(ui_brakeseparator, -18);
    lv_obj_set_align(ui_brakeseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_brakeseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_brakeseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_brakeseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_brakeseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_botonshowajustes2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_botonshowajustes2, 800);
    lv_obj_set_height(ui_botonshowajustes2, 480);
    lv_obj_set_x(ui_botonshowajustes2, 1);
    lv_obj_set_y(ui_botonshowajustes2, 0);
    lv_obj_set_align(ui_botonshowajustes2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botonshowajustes2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botonshowajustes2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_botonshowajustes2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_botonshowajustes2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ajustesboton2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ajustesboton2, 150);
    lv_obj_set_height(ui_ajustesboton2, 70);
    lv_obj_set_x(ui_ajustesboton2, 303);
    lv_obj_set_y(ui_ajustesboton2, -190);
    lv_obj_set_align(ui_ajustesboton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ajustesboton2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ajustesboton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ajustesboton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ajustesboton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_ajustesboton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_ajustesboton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_ajustesboton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_border_width(ui_ajustesboton2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ajustesnombre2 = lv_label_create(ui_ajustesboton2);
    lv_obj_set_width(ui_ajustesnombre2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ajustesnombre2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ajustesnombre2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ajustesnombre2, "Ajustes");
    ui_object_set_themeable_style_property(ui_ajustesnombre2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_ajustesnombre2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_ajustesnombre2, &ui_font_ajustesnames, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_botonshowajustes2, ui_event_botonshowajustes2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ajustesboton2, ui_event_ajustesboton2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_aux1panel = NULL;
    ui_aux1name = NULL;
    ui_aux1 = NULL;
    ui_aux1separator = NULL;
    ui_aux3panel = NULL;
    ui_aux3name = NULL;
    ui_aux3 = NULL;
    ui_aux3separator = NULL;
    ui_aux4panel = NULL;
    ui_aux4name = NULL;
    ui_aux4 = NULL;
    ui_aux4separator = NULL;
    ui_aux5panel = NULL;
    ui_aux5name = NULL;
    ui_aux5 = NULL;
    ui_aux5separator = NULL;
    ui_aux6panel = NULL;
    ui_aux6name = NULL;
    ui_aux6 = NULL;
    ui_aux6separator = NULL;
    ui_aux7panel = NULL;
    ui_aux7name = NULL;
    ui_aux7 = NULL;
    ui_aux7separator = NULL;
    ui_aux8panel = NULL;
    ui_aux8name = NULL;
    ui_aux8 = NULL;
    ui_aux8separator = NULL;
    ui_dig1panel = NULL;
    ui_dig1name = NULL;
    ui_dig1 = NULL;
    ui_dig1separator = NULL;
    ui_throttlepanel = NULL;
    ui_throttlename = NULL;
    ui_throttle = NULL;
    ui_throttleseparator = NULL;
    ui_nousepanel = NULL;
    ui_nousename = NULL;
    ui_nouse = NULL;
    ui_nouseseparator = NULL;
    ui_lambdtrgapanel = NULL;
    ui_lambdatrgname = NULL;
    ui_lambdatrg = NULL;
    ui_lambdatrgseparator = NULL;
    ui_mappanel = NULL;
    ui_mapname = NULL;
    ui_map = NULL;
    ui_mapseparator = NULL;
    ui_brakepanel = NULL;
    ui_brakename = NULL;
    ui_brake = NULL;
    ui_brakeseparator = NULL;
    ui_botonshowajustes2 = NULL;
    ui_ajustesboton2 = NULL;
    ui_ajustesnombre2 = NULL;

}
