// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#include "../../include/ui/ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_main = NULL;
lv_obj_t * ui_barcontainer = NULL;
lv_obj_t * ui_rpm0 = NULL;
lv_obj_t * ui_rpmt0 = NULL;
lv_obj_t * ui_rpm1 = NULL;
lv_obj_t * ui_rpm2 = NULL;
lv_obj_t * ui_rpmt1 = NULL;
lv_obj_t * ui_rpm3 = NULL;
lv_obj_t * ui_rpm4 = NULL;
lv_obj_t * ui_rpmt2 = NULL;
lv_obj_t * ui_rpm5 = NULL;
lv_obj_t * ui_rpm6 = NULL;
lv_obj_t * ui_rpmt3 = NULL;
lv_obj_t * ui_rpm7 = NULL;
lv_obj_t * ui_rpm8 = NULL;
lv_obj_t * ui_rpmt4 = NULL;
lv_obj_t * ui_rpm9 = NULL;
lv_obj_t * ui_rpm10 = NULL;
lv_obj_t * ui_rpmt5 = NULL;
lv_obj_t * ui_rpm11 = NULL;
lv_obj_t * ui_rpm12 = NULL;
lv_obj_t * ui_rpmt6 = NULL;
lv_obj_t * ui_rpm13 = NULL;
lv_obj_t * ui_rpmt16 = NULL;
lv_obj_t * ui_rpmt7 = NULL;
lv_obj_t * ui_rpmt8 = NULL;
lv_obj_t * ui_rpmt9 = NULL;
lv_obj_t * ui_rpmt10 = NULL;
lv_obj_t * ui_rpmt11 = NULL;
lv_obj_t * ui_rpmt12 = NULL;
lv_obj_t * ui_rpmbaja1 = NULL;
lv_obj_t * ui_rpmbaja2 = NULL;
lv_obj_t * ui_rpmbaja3 = NULL;
lv_obj_t * ui_rpmbaja4 = NULL;
lv_obj_t * ui_rpmbaja5 = NULL;
lv_obj_t * ui_rpmbaja6 = NULL;
lv_obj_t * ui_rpmbaja7 = NULL;
lv_obj_t * ui_tiraledsrpmcontainer = NULL;
lv_obj_t * ui_led0 = NULL;
lv_obj_t * ui_led1 = NULL;
lv_obj_t * ui_led2 = NULL;
lv_obj_t * ui_led3 = NULL;
lv_obj_t * ui_led4 = NULL;
lv_obj_t * ui_led5 = NULL;
lv_obj_t * ui_led6 = NULL;
lv_obj_t * ui_led7 = NULL;
lv_obj_t * ui_led8 = NULL;
lv_obj_t * ui_led9 = NULL;
lv_obj_t * ui_led10 = NULL;
lv_obj_t * ui_led11 = NULL;
lv_obj_t * ui_led12 = NULL;
lv_obj_t * ui_led13 = NULL;
lv_obj_t * ui_led14 = NULL;
lv_obj_t * ui_barrpm = NULL;
lv_obj_t * ui_rpma = NULL;
lv_obj_t * ui_rpmb = NULL;
lv_obj_t * ui_rpmname = NULL;
lv_obj_t * ui_rpm = NULL;
lv_obj_t * ui_oiltpanel = NULL;
lv_obj_t * ui_oilt = NULL;
lv_obj_t * ui_oiltname = NULL;
lv_obj_t * ui_oiltseparator = NULL;
lv_obj_t * ui_oilppanel = NULL;
lv_obj_t * ui_oilp = NULL;
lv_obj_t * ui_oilpseparator = NULL;
lv_obj_t * ui_oilpname = NULL;
lv_obj_t * ui_fuelppanel = NULL;
lv_obj_t * ui_fuelp = NULL;
lv_obj_t * ui_fuelpseparator = NULL;
lv_obj_t * ui_fuelpname = NULL;
lv_obj_t * ui_lambdapanel = NULL;
lv_obj_t * ui_lambda = NULL;
lv_obj_t * ui_lambdaname = NULL;
lv_obj_t * ui_lambdaseparator = NULL;
lv_obj_t * ui_watertpanel = NULL;
lv_obj_t * ui_watert = NULL;
lv_obj_t * ui_watertseparator = NULL;
lv_obj_t * ui_watertname = NULL;
lv_obj_t * ui_sdownpanel = NULL;
lv_obj_t * ui_sdownname = NULL;
lv_obj_t * ui_sdown = NULL;
lv_obj_t * ui_sdownseparator = NULL;
lv_obj_t * ui_vbatpanel = NULL;
lv_obj_t * ui_vbat = NULL;
lv_obj_t * ui_vbatseparator = NULL;
lv_obj_t * ui_vbatname = NULL;
lv_obj_t * ui_fanpanel = NULL;
lv_obj_t * ui_fanname = NULL;
lv_obj_t * ui_fan = NULL;
lv_obj_t * ui_fanseparator = NULL;
lv_obj_t * ui_neutralpanel = NULL;
lv_obj_t * ui_neutral = NULL;
lv_obj_t * ui_warmuppanel = NULL;
lv_obj_t * ui_warmup = NULL;
lv_obj_t * ui_botonshowajustes = NULL;
lv_obj_t * ui_ajustesboton = NULL;
lv_obj_t * ui_ajustesnombre = NULL;
// event funtions
void ui_event_botonshowajustes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_ajustesboton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ajustesboton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingscreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settingscreen_screen_init);
        _ui_flag_modify(ui_ajustesboton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        abrirajustes(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);

    ui_main = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_main);
    lv_obj_set_width(ui_main, 800);
    lv_obj_set_height(ui_main, 480);
    lv_obj_set_align(ui_main, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_barcontainer = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_barcontainer);
    lv_obj_set_width(ui_barcontainer, 800);
    lv_obj_set_height(ui_barcontainer, 480);
    lv_obj_set_align(ui_barcontainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barcontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_barcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rpm0 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm0, 3);
    lv_obj_set_height(ui_rpm0, 22);
    lv_obj_set_x(ui_rpm0, -385);
    lv_obj_set_y(ui_rpm0, -190);
    lv_obj_set_align(ui_rpm0, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmt0 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt0, -385);
    lv_obj_set_y(ui_rpmt0, -218);
    lv_obj_set_align(ui_rpmt0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt0, "0");
    ui_object_set_themeable_style_property(ui_rpmt0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt0, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm1 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm1, 3);
    lv_obj_set_height(ui_rpm1, 22);
    lv_obj_set_x(ui_rpm1, -354);
    lv_obj_set_y(ui_rpm1, -190);
    lv_obj_set_align(ui_rpm1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpm2 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm2, 3);
    lv_obj_set_height(ui_rpm2, 22);
    lv_obj_set_x(ui_rpm2, -323);
    lv_obj_set_y(ui_rpm2, -190);
    lv_obj_set_align(ui_rpm2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmt1 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt1, -354);
    lv_obj_set_y(ui_rpmt1, -218);
    lv_obj_set_align(ui_rpmt1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt1, "1");
    ui_object_set_themeable_style_property(ui_rpmt1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt1, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm3 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm3, 3);
    lv_obj_set_height(ui_rpm3, 22);
    lv_obj_set_x(ui_rpm3, -291);
    lv_obj_set_y(ui_rpm3, -190);
    lv_obj_set_align(ui_rpm3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_object_set_themeable_style_property(ui_rpm3, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm3, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpm4 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm4, 3);
    lv_obj_set_height(ui_rpm4, 22);
    lv_obj_set_x(ui_rpm4, -260);
    lv_obj_set_y(ui_rpm4, -190);
    lv_obj_set_align(ui_rpm4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmt2 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt2, -323);
    lv_obj_set_y(ui_rpmt2, -218);
    lv_obj_set_align(ui_rpmt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt2, "2");
    ui_object_set_themeable_style_property(ui_rpmt2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt2, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm5 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm5, 3);
    lv_obj_set_height(ui_rpm5, 22);
    lv_obj_set_x(ui_rpm5, -229);
    lv_obj_set_y(ui_rpm5, -190);
    lv_obj_set_align(ui_rpm5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpm6 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm6, 3);
    lv_obj_set_height(ui_rpm6, 22);
    lv_obj_set_x(ui_rpm6, -198);
    lv_obj_set_y(ui_rpm6, -190);
    lv_obj_set_align(ui_rpm6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmt3 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt3, -291);
    lv_obj_set_y(ui_rpmt3, -218);
    lv_obj_set_align(ui_rpmt3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt3, "3");
    ui_object_set_themeable_style_property(ui_rpmt3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt3, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm7 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm7, 3);
    lv_obj_set_height(ui_rpm7, 22);
    lv_obj_set_x(ui_rpm7, -118);
    lv_obj_set_y(ui_rpm7, -190);
    lv_obj_set_align(ui_rpm7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpm8 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm8, 3);
    lv_obj_set_height(ui_rpm8, 22);
    lv_obj_set_x(ui_rpm8, -37);
    lv_obj_set_y(ui_rpm8, -190);
    lv_obj_set_align(ui_rpm8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmt4 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt4, -260);
    lv_obj_set_y(ui_rpmt4, -218);
    lv_obj_set_align(ui_rpmt4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt4, "4");
    ui_object_set_themeable_style_property(ui_rpmt4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt4, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm9 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm9, 3);
    lv_obj_set_height(ui_rpm9, 22);
    lv_obj_set_x(ui_rpm9, 43);
    lv_obj_set_y(ui_rpm9, -190);
    lv_obj_set_align(ui_rpm9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpm10 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm10, 3);
    lv_obj_set_height(ui_rpm10, 22);
    lv_obj_set_x(ui_rpm10, 124);
    lv_obj_set_y(ui_rpm10, -190);
    lv_obj_set_align(ui_rpm10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmt5 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt5, -229);
    lv_obj_set_y(ui_rpmt5, -218);
    lv_obj_set_align(ui_rpmt5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt5, "5");
    ui_object_set_themeable_style_property(ui_rpmt5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt5, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm11 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm11, 3);
    lv_obj_set_height(ui_rpm11, 22);
    lv_obj_set_x(ui_rpm11, 204);
    lv_obj_set_y(ui_rpm11, -190);
    lv_obj_set_align(ui_rpm11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpm12 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm12, 3);
    lv_obj_set_height(ui_rpm12, 22);
    lv_obj_set_x(ui_rpm12, 285);
    lv_obj_set_y(ui_rpm12, -190);
    lv_obj_set_align(ui_rpm12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpm12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmt6 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt6, -198);
    lv_obj_set_y(ui_rpmt6, -218);
    lv_obj_set_align(ui_rpmt6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt6, "6");
    ui_object_set_themeable_style_property(ui_rpmt6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt6, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm13 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpm13, 3);
    lv_obj_set_height(ui_rpm13, 22);
    lv_obj_set_x(ui_rpm13, 365);
    lv_obj_set_y(ui_rpm13, -190);
    lv_obj_set_align(ui_rpm13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpm13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_rpm13, lv_color_hex(0xDE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rpm13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmt16 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt16, 365);
    lv_obj_set_y(ui_rpmt16, -218);
    lv_obj_set_align(ui_rpmt16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt16, "13000");
    lv_obj_set_style_text_color(ui_rpmt16, lv_color_hex(0xDE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmt16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmt16, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmt7 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt7, -118);
    lv_obj_set_y(ui_rpmt7, -218);
    lv_obj_set_align(ui_rpmt7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt7, "7000");
    ui_object_set_themeable_style_property(ui_rpmt7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt7, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmt8 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt8, -37);
    lv_obj_set_y(ui_rpmt8, -218);
    lv_obj_set_align(ui_rpmt8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt8, "8000");
    ui_object_set_themeable_style_property(ui_rpmt8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt8, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmt9 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt9, 43);
    lv_obj_set_y(ui_rpmt9, -218);
    lv_obj_set_align(ui_rpmt9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt9, "9000");
    ui_object_set_themeable_style_property(ui_rpmt9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt9, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmt10 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt10, 124);
    lv_obj_set_y(ui_rpmt10, -218);
    lv_obj_set_align(ui_rpmt10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt10, "10000");
    ui_object_set_themeable_style_property(ui_rpmt10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt10, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmt11 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt11, 204);
    lv_obj_set_y(ui_rpmt11, -218);
    lv_obj_set_align(ui_rpmt11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt11, "11000");
    ui_object_set_themeable_style_property(ui_rpmt11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt11, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmt12 = lv_label_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmt12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmt12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmt12, 285);
    lv_obj_set_y(ui_rpmt12, -218);
    lv_obj_set_align(ui_rpmt12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmt12, "12000");
    ui_object_set_themeable_style_property(ui_rpmt12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmt12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmt12, &ui_font_rpm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmbaja1 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmbaja1, 3);
    lv_obj_set_height(ui_rpmbaja1, 12);
    lv_obj_set_x(ui_rpmbaja1, -158);
    lv_obj_set_y(ui_rpmbaja1, -186);
    lv_obj_set_align(ui_rpmbaja1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmbaja1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpmbaja1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmbaja1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmbaja2 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmbaja2, 3);
    lv_obj_set_height(ui_rpmbaja2, 12);
    lv_obj_set_x(ui_rpmbaja2, -77);
    lv_obj_set_y(ui_rpmbaja2, -186);
    lv_obj_set_align(ui_rpmbaja2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmbaja2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpmbaja2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmbaja2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmbaja3 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmbaja3, 3);
    lv_obj_set_height(ui_rpmbaja3, 12);
    lv_obj_set_x(ui_rpmbaja3, 3);
    lv_obj_set_y(ui_rpmbaja3, -186);
    lv_obj_set_align(ui_rpmbaja3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmbaja3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpmbaja3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmbaja3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmbaja4 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmbaja4, 3);
    lv_obj_set_height(ui_rpmbaja4, 12);
    lv_obj_set_x(ui_rpmbaja4, 83);
    lv_obj_set_y(ui_rpmbaja4, -186);
    lv_obj_set_align(ui_rpmbaja4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmbaja4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpmbaja4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmbaja4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmbaja5 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmbaja5, 3);
    lv_obj_set_height(ui_rpmbaja5, 12);
    lv_obj_set_x(ui_rpmbaja5, 164);
    lv_obj_set_y(ui_rpmbaja5, -186);
    lv_obj_set_align(ui_rpmbaja5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmbaja5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpmbaja5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmbaja5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmbaja6 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmbaja6, 3);
    lv_obj_set_height(ui_rpmbaja6, 12);
    lv_obj_set_x(ui_rpmbaja6, 244);
    lv_obj_set_y(ui_rpmbaja6, -186);
    lv_obj_set_align(ui_rpmbaja6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmbaja6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpmbaja6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmbaja6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmbaja7 = lv_obj_create(ui_barcontainer);
    lv_obj_set_width(ui_rpmbaja7, 3);
    lv_obj_set_height(ui_rpmbaja7, 12);
    lv_obj_set_x(ui_rpmbaja7, 325);
    lv_obj_set_y(ui_rpmbaja7, -186);
    lv_obj_set_align(ui_rpmbaja7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmbaja7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_rpmbaja7, lv_color_hex(0xDE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rpmbaja7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tiraledsrpmcontainer = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_tiraledsrpmcontainer, 800);
    lv_obj_set_height(ui_tiraledsrpmcontainer, 56);
    lv_obj_set_x(ui_tiraledsrpmcontainer, 0);
    lv_obj_set_y(ui_tiraledsrpmcontainer, -212);
    lv_obj_set_align(ui_tiraledsrpmcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tiraledsrpmcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_led0 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led0, 46);
    lv_obj_set_height(ui_led0, 40);
    lv_obj_set_x(ui_led0, -357);
    lv_obj_set_y(ui_led0, 0);
    lv_obj_set_align(ui_led0, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led0, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led1 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led1, 46);
    lv_obj_set_height(ui_led1, 40);
    lv_obj_set_x(ui_led1, -306);
    lv_obj_set_y(ui_led1, 0);
    lv_obj_set_align(ui_led1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led2 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led2, 46);
    lv_obj_set_height(ui_led2, 40);
    lv_obj_set_x(ui_led2, -255);
    lv_obj_set_y(ui_led2, 0);
    lv_obj_set_align(ui_led2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led3 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led3, 46);
    lv_obj_set_height(ui_led3, 40);
    lv_obj_set_x(ui_led3, -204);
    lv_obj_set_y(ui_led3, 0);
    lv_obj_set_align(ui_led3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led4 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led4, 46);
    lv_obj_set_height(ui_led4, 40);
    lv_obj_set_x(ui_led4, -153);
    lv_obj_set_y(ui_led4, 0);
    lv_obj_set_align(ui_led4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led5 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led5, 46);
    lv_obj_set_height(ui_led5, 40);
    lv_obj_set_x(ui_led5, -102);
    lv_obj_set_y(ui_led5, 0);
    lv_obj_set_align(ui_led5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led6 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led6, 46);
    lv_obj_set_height(ui_led6, 40);
    lv_obj_set_x(ui_led6, -51);
    lv_obj_set_y(ui_led6, 0);
    lv_obj_set_align(ui_led6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led7 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led7, 46);
    lv_obj_set_height(ui_led7, 40);
    lv_obj_set_align(ui_led7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led8 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led8, 46);
    lv_obj_set_height(ui_led8, 40);
    lv_obj_set_x(ui_led8, 51);
    lv_obj_set_y(ui_led8, 0);
    lv_obj_set_align(ui_led8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led9 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led9, 46);
    lv_obj_set_height(ui_led9, 40);
    lv_obj_set_x(ui_led9, 102);
    lv_obj_set_y(ui_led9, 0);
    lv_obj_set_align(ui_led9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led10 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led10, 46);
    lv_obj_set_height(ui_led10, 40);
    lv_obj_set_x(ui_led10, 153);
    lv_obj_set_y(ui_led10, 0);
    lv_obj_set_align(ui_led10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led11 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led11, 46);
    lv_obj_set_height(ui_led11, 40);
    lv_obj_set_x(ui_led11, 204);
    lv_obj_set_y(ui_led11, 0);
    lv_obj_set_align(ui_led11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led12 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led12, 46);
    lv_obj_set_height(ui_led12, 40);
    lv_obj_set_x(ui_led12, 255);
    lv_obj_set_y(ui_led12, 0);
    lv_obj_set_align(ui_led12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led13 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led13, 46);
    lv_obj_set_height(ui_led13, 40);
    lv_obj_set_x(ui_led13, 306);
    lv_obj_set_y(ui_led13, 0);
    lv_obj_set_align(ui_led13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led14 = lv_obj_create(ui_tiraledsrpmcontainer);
    lv_obj_set_width(ui_led14, 46);
    lv_obj_set_height(ui_led14, 40);
    lv_obj_set_x(ui_led14, 357);
    lv_obj_set_y(ui_led14, 0);
    lv_obj_set_align(ui_led14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_led14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_led14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_led14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_led14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    lv_obj_set_style_border_width(ui_led14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barrpm = lv_bar_create(ui_main);
    lv_bar_set_value(ui_barrpm, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barrpm, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barrpm, 770);
    lv_obj_set_height(ui_barrpm, 36);
    lv_obj_set_x(ui_barrpm, 0);
    lv_obj_set_y(ui_barrpm, -154);
    lv_obj_set_align(ui_barrpm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barrpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_barrpm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fbarra);
    ui_object_set_themeable_style_property(ui_barrpm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fbarra);
    ui_object_set_themeable_style_property(ui_barrpm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_barrar);
    lv_obj_set_style_bg_main_stop(ui_barrpm, 229, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_barrpm, 229, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_barrpm, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barrpm, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_barrpm, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_barrpm, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpma = lv_obj_create(ui_main);
    lv_obj_set_width(ui_rpma, 770);
    lv_obj_set_height(ui_rpma, 2);
    lv_obj_set_x(ui_rpma, 0);
    lv_obj_set_y(ui_rpma, -180);
    lv_obj_set_align(ui_rpma, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpma, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpma, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpma, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmb = lv_obj_create(ui_main);
    lv_obj_set_width(ui_rpmb, 770);
    lv_obj_set_height(ui_rpmb, 2);
    lv_obj_set_x(ui_rpmb, 0);
    lv_obj_set_y(ui_rpmb, -128);
    lv_obj_set_align(ui_rpmb, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_rpmb, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmb, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_rpmname = lv_label_create(ui_main);
    lv_obj_set_width(ui_rpmname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmname, 0);
    lv_obj_set_y(ui_rpmname, -107);
    lv_obj_set_align(ui_rpmname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpmname, "RPM");
    ui_object_set_themeable_style_property(ui_rpmname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpmname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpmname, &ui_font_speedlabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm = lv_label_create(ui_main);
    lv_obj_set_width(ui_rpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm, 0);
    lv_obj_set_y(ui_rpm, -46);
    lv_obj_set_align(ui_rpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm, "-");
    ui_object_set_themeable_style_property(ui_rpm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_rpm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_rpm, &ui_font_speed, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oiltpanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_oiltpanel, 244);
    lv_obj_set_height(ui_oiltpanel, 116);
    lv_obj_set_x(ui_oiltpanel, -270);
    lv_obj_set_y(ui_oiltpanel, 15);
    lv_obj_set_align(ui_oiltpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_oiltpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_oiltpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_oiltpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_oiltpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_oiltpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_oiltpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_oilt = lv_label_create(ui_oiltpanel);
    lv_obj_set_width(ui_oilt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilt, 0);
    lv_obj_set_y(ui_oilt, 22);
    lv_obj_set_align(ui_oilt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oilt, "-");
    ui_object_set_themeable_style_property(ui_oilt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_oilt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_oilt, &ui_font_labeld, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oiltname = lv_label_create(ui_oiltpanel);
    lv_obj_set_width(ui_oiltname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oiltname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oiltname, 0);
    lv_obj_set_y(ui_oiltname, -38);
    lv_obj_set_align(ui_oiltname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oiltname, "OIL TEMP");
    ui_object_set_themeable_style_property(ui_oiltname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_oiltname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_oiltname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oiltseparator = lv_obj_create(ui_oiltpanel);
    lv_obj_set_width(ui_oiltseparator, 150);
    lv_obj_set_height(ui_oiltseparator, 1);
    lv_obj_set_x(ui_oiltseparator, 0);
    lv_obj_set_y(ui_oiltseparator, -21);
    lv_obj_set_align(ui_oiltseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_oiltseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_oiltseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_oiltseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_oiltseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_oilppanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_oilppanel, 244);
    lv_obj_set_height(ui_oilppanel, 116);
    lv_obj_set_x(ui_oilppanel, -270);
    lv_obj_set_y(ui_oilppanel, 129);
    lv_obj_set_align(ui_oilppanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_oilppanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_oilppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_oilppanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_oilppanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_oilppanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_oilppanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_oilp = lv_label_create(ui_oilppanel);
    lv_obj_set_width(ui_oilp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilp, 0);
    lv_obj_set_y(ui_oilp, 22);
    lv_obj_set_align(ui_oilp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oilp, "-");
    ui_object_set_themeable_style_property(ui_oilp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_oilp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_oilp, &ui_font_labeld, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilpseparator = lv_obj_create(ui_oilppanel);
    lv_obj_set_width(ui_oilpseparator, 150);
    lv_obj_set_height(ui_oilpseparator, 1);
    lv_obj_set_x(ui_oilpseparator, 0);
    lv_obj_set_y(ui_oilpseparator, -21);
    lv_obj_set_align(ui_oilpseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_oilpseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_oilpseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilpseparator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilpseparator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_oilpseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_oilpseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_oilpname = lv_label_create(ui_oilppanel);
    lv_obj_set_width(ui_oilpname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilpname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilpname, 0);
    lv_obj_set_y(ui_oilpname, -38);
    lv_obj_set_align(ui_oilpname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oilpname, "OIL PRESS");
    ui_object_set_themeable_style_property(ui_oilpname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_oilpname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_oilpname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelppanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_fuelppanel, 300);
    lv_obj_set_height(ui_fuelppanel, 116);
    lv_obj_set_x(ui_fuelppanel, 0);
    lv_obj_set_y(ui_fuelppanel, 176);
    lv_obj_set_align(ui_fuelppanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fuelppanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fuelppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_fuelppanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_fuelppanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_fuelppanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_fuelppanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_fuelp = lv_label_create(ui_fuelppanel);
    lv_obj_set_width(ui_fuelp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuelp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuelp, 0);
    lv_obj_set_y(ui_fuelp, 22);
    lv_obj_set_align(ui_fuelp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuelp, "-");
    ui_object_set_themeable_style_property(ui_fuelp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_fuelp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_fuelp, &ui_font_labeld, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelpseparator = lv_obj_create(ui_fuelppanel);
    lv_obj_set_width(ui_fuelpseparator, 150);
    lv_obj_set_height(ui_fuelpseparator, 1);
    lv_obj_set_x(ui_fuelpseparator, 0);
    lv_obj_set_y(ui_fuelpseparator, -21);
    lv_obj_set_align(ui_fuelpseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fuelpseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fuelpseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuelpseparator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelpseparator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_fuelpseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_fuelpseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_fuelpname = lv_label_create(ui_fuelppanel);
    lv_obj_set_width(ui_fuelpname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuelpname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuelpname, 0);
    lv_obj_set_y(ui_fuelpname, -38);
    lv_obj_set_align(ui_fuelpname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuelpname, "FUEL PRESS");
    ui_object_set_themeable_style_property(ui_fuelpname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_fuelpname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_fuelpname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lambdapanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_lambdapanel, 300);
    lv_obj_set_height(ui_lambdapanel, 116);
    lv_obj_set_x(ui_lambdapanel, 0);
    lv_obj_set_y(ui_lambdapanel, 62);
    lv_obj_set_align(ui_lambdapanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lambdapanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lambdapanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lambdapanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_lambdapanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_lambdapanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_lambdapanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_lambda = lv_label_create(ui_lambdapanel);
    lv_obj_set_width(ui_lambda, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lambda, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lambda, 0);
    lv_obj_set_y(ui_lambda, 22);
    lv_obj_set_align(ui_lambda, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lambda, "-");
    ui_object_set_themeable_style_property(ui_lambda, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_lambda, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_lambda, &ui_font_labeld, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lambdaname = lv_label_create(ui_lambdapanel);
    lv_obj_set_width(ui_lambdaname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lambdaname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lambdaname, 0);
    lv_obj_set_y(ui_lambdaname, -38);
    lv_obj_set_align(ui_lambdaname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lambdaname, "LAMBDA");
    ui_object_set_themeable_style_property(ui_lambdaname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_lambdaname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_lambdaname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lambdaseparator = lv_obj_create(ui_lambdapanel);
    lv_obj_set_width(ui_lambdaseparator, 150);
    lv_obj_set_height(ui_lambdaseparator, 1);
    lv_obj_set_x(ui_lambdaseparator, 0);
    lv_obj_set_y(ui_lambdaseparator, -21);
    lv_obj_set_align(ui_lambdaseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lambdaseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lambdaseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lambdaseparator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lambdaseparator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lambdaseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_lambdaseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_watertpanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_watertpanel, 244);
    lv_obj_set_height(ui_watertpanel, 116);
    lv_obj_set_x(ui_watertpanel, 270);
    lv_obj_set_y(ui_watertpanel, 15);
    lv_obj_set_align(ui_watertpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_watertpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_watertpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_watertpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_watertpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_watertpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_watertpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_watert = lv_label_create(ui_watertpanel);
    lv_obj_set_width(ui_watert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watert, 0);
    lv_obj_set_y(ui_watert, 22);
    lv_obj_set_align(ui_watert, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watert, "-");
    ui_object_set_themeable_style_property(ui_watert, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_watert, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_watert, &ui_font_labeld, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watertseparator = lv_obj_create(ui_watertpanel);
    lv_obj_set_width(ui_watertseparator, 150);
    lv_obj_set_height(ui_watertseparator, 1);
    lv_obj_set_x(ui_watertseparator, 0);
    lv_obj_set_y(ui_watertseparator, -21);
    lv_obj_set_align(ui_watertseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_watertseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_watertseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_watertseparator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watertseparator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_watertseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_watertseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_watertname = lv_label_create(ui_watertpanel);
    lv_obj_set_width(ui_watertname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watertname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watertname, 0);
    lv_obj_set_y(ui_watertname, -38);
    lv_obj_set_align(ui_watertname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watertname, "WATER TEMP");
    ui_object_set_themeable_style_property(ui_watertname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_watertname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_watertname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdownpanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_sdownpanel, 122);
    lv_obj_set_height(ui_sdownpanel, 70);
    lv_obj_set_x(ui_sdownpanel, 209);
    lv_obj_set_y(ui_sdownpanel, -76);
    lv_obj_set_align(ui_sdownpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sdownpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sdownpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sdownpanel, lv_color_hex(0x9E3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sdownpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_sdownpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_sdownpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_sdownname = lv_label_create(ui_sdownpanel);
    lv_obj_set_width(ui_sdownname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sdownname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sdownname, 0);
    lv_obj_set_y(ui_sdownname, -20);
    lv_obj_set_align(ui_sdownname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sdownname, "S.DOWN");
    ui_object_set_themeable_style_property(ui_sdownname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_sdownname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_sdownname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdown = lv_label_create(ui_sdownpanel);
    lv_obj_set_width(ui_sdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sdown, 0);
    lv_obj_set_y(ui_sdown, 15);
    lv_obj_set_align(ui_sdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sdown, "OFF");
    ui_object_set_themeable_style_property(ui_sdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_sdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_sdown, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sdownseparator = lv_obj_create(ui_sdownpanel);
    lv_obj_set_width(ui_sdownseparator, 70);
    lv_obj_set_height(ui_sdownseparator, 1);
    lv_obj_set_x(ui_sdownseparator, 0);
    lv_obj_set_y(ui_sdownseparator, -7);
    lv_obj_set_align(ui_sdownseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sdownseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sdownseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sdownseparator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sdownseparator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_sdownseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_sdownseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_vbatpanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_vbatpanel, 244);
    lv_obj_set_height(ui_vbatpanel, 116);
    lv_obj_set_x(ui_vbatpanel, 270);
    lv_obj_set_y(ui_vbatpanel, 129);
    lv_obj_set_align(ui_vbatpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_vbatpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vbatpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_vbatpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_vbatpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_vbatpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_vbatpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_vbat = lv_label_create(ui_vbatpanel);
    lv_obj_set_width(ui_vbat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vbat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vbat, 0);
    lv_obj_set_y(ui_vbat, 22);
    lv_obj_set_align(ui_vbat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vbat, "-");
    ui_object_set_themeable_style_property(ui_vbat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_vbat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_vbat, &ui_font_labeld, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vbatseparator = lv_obj_create(ui_vbatpanel);
    lv_obj_set_width(ui_vbatseparator, 150);
    lv_obj_set_height(ui_vbatseparator, 1);
    lv_obj_set_x(ui_vbatseparator, 0);
    lv_obj_set_y(ui_vbatseparator, -21);
    lv_obj_set_align(ui_vbatseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_vbatseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vbatseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vbatseparator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vbatseparator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_vbatseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_vbatseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_vbatname = lv_label_create(ui_vbatpanel);
    lv_obj_set_width(ui_vbatname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vbatname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vbatname, 0);
    lv_obj_set_y(ui_vbatname, -38);
    lv_obj_set_align(ui_vbatname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vbatname, "V BATT");
    ui_object_set_themeable_style_property(ui_vbatname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_vbatname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_vbatname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fanpanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_fanpanel, 122);
    lv_obj_set_height(ui_fanpanel, 70);
    lv_obj_set_x(ui_fanpanel, 329);
    lv_obj_set_y(ui_fanpanel, -76);
    lv_obj_set_align(ui_fanpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fanpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fanpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fanpanel, lv_color_hex(0x458F45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fanpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_fanpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_fanpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_fanname = lv_label_create(ui_fanpanel);
    lv_obj_set_width(ui_fanname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fanname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fanname, 0);
    lv_obj_set_y(ui_fanname, -20);
    lv_obj_set_align(ui_fanname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fanname, "FAN");
    ui_object_set_themeable_style_property(ui_fanname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_fanname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_fanname, &ui_font_labelt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fan = lv_label_create(ui_fanpanel);
    lv_obj_set_width(ui_fan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan, 0);
    lv_obj_set_y(ui_fan, 15);
    lv_obj_set_align(ui_fan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fan, "ON");
    ui_object_set_themeable_style_property(ui_fan, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_fan, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_fan, &ui_font_offon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fanseparator = lv_obj_create(ui_fanpanel);
    lv_obj_set_width(ui_fanseparator, 70);
    lv_obj_set_height(ui_fanseparator, 1);
    lv_obj_set_x(ui_fanseparator, 0);
    lv_obj_set_y(ui_fanseparator, -7);
    lv_obj_set_align(ui_fanseparator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fanseparator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fanseparator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fanseparator, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fanseparator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_fanseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_fanseparator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_neutralpanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_neutralpanel, 70);
    lv_obj_set_height(ui_neutralpanel, 39);
    lv_obj_set_x(ui_neutralpanel, -270);
    lv_obj_set_y(ui_neutralpanel, -88);
    lv_obj_set_align(ui_neutralpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_neutralpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_neutralpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_neutralpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_neutralpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_neutralpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_neutralpanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);

    ui_neutral = lv_label_create(ui_neutralpanel);
    lv_obj_set_width(ui_neutral, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_neutral, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_neutral, LV_ALIGN_CENTER);
    lv_label_set_text(ui_neutral, "N");
    ui_object_set_themeable_style_property(ui_neutral, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_neutral, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_neutral, &ui_font_neutral, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_warmuppanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_warmuppanel, 180);
    lv_obj_set_height(ui_warmuppanel, 28);
    lv_obj_set_x(ui_warmuppanel, 0);
    lv_obj_set_y(ui_warmuppanel, -154);
    lv_obj_set_align(ui_warmuppanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_warmuppanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_warmuppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_warmuppanel, lv_color_hex(0xCF7000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_warmuppanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_warmuppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_warmup = lv_label_create(ui_main);
    lv_obj_set_width(ui_warmup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_warmup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_warmup, 0);
    lv_obj_set_y(ui_warmup, -154);
    lv_obj_set_align(ui_warmup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_warmup, "WARM UP!");
    lv_obj_set_style_text_color(ui_warmup, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_warmup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_warmup, &ui_font_warmup, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botonshowajustes = lv_btn_create(ui_main);
    lv_obj_set_width(ui_botonshowajustes, 800);
    lv_obj_set_height(ui_botonshowajustes, 480);
    lv_obj_set_align(ui_botonshowajustes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botonshowajustes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botonshowajustes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_botonshowajustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_botonshowajustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ajustesboton = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_ajustesboton, 150);
    lv_obj_set_height(ui_ajustesboton, 70);
    lv_obj_set_x(ui_ajustesboton, 303);
    lv_obj_set_y(ui_ajustesboton, -190);
    lv_obj_set_align(ui_ajustesboton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ajustesboton, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ajustesboton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ajustesboton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ajustesboton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fondo);
    ui_object_set_themeable_style_property(ui_ajustesboton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fondo);
    ui_object_set_themeable_style_property(ui_ajustesboton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_ajustesboton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_border_width(ui_ajustesboton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ajustesnombre = lv_label_create(ui_ajustesboton);
    lv_obj_set_width(ui_ajustesnombre, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ajustesnombre, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ajustesnombre, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ajustesnombre, "Ajustes");
    ui_object_set_themeable_style_property(ui_ajustesnombre, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texto);
    ui_object_set_themeable_style_property(ui_ajustesnombre, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texto);
    lv_obj_set_style_text_font(ui_ajustesnombre, &ui_font_ajustesnames, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_botonshowajustes, ui_event_botonshowajustes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ajustesboton, ui_event_ajustesboton, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_main = NULL;
    ui_barcontainer = NULL;
    ui_rpm0 = NULL;
    ui_rpmt0 = NULL;
    ui_rpm1 = NULL;
    ui_rpm2 = NULL;
    ui_rpmt1 = NULL;
    ui_rpm3 = NULL;
    ui_rpm4 = NULL;
    ui_rpmt2 = NULL;
    ui_rpm5 = NULL;
    ui_rpm6 = NULL;
    ui_rpmt3 = NULL;
    ui_rpm7 = NULL;
    ui_rpm8 = NULL;
    ui_rpmt4 = NULL;
    ui_rpm9 = NULL;
    ui_rpm10 = NULL;
    ui_rpmt5 = NULL;
    ui_rpm11 = NULL;
    ui_rpm12 = NULL;
    ui_rpmt6 = NULL;
    ui_rpm13 = NULL;
    ui_rpmt16 = NULL;
    ui_rpmt7 = NULL;
    ui_rpmt8 = NULL;
    ui_rpmt9 = NULL;
    ui_rpmt10 = NULL;
    ui_rpmt11 = NULL;
    ui_rpmt12 = NULL;
    ui_rpmbaja1 = NULL;
    ui_rpmbaja2 = NULL;
    ui_rpmbaja3 = NULL;
    ui_rpmbaja4 = NULL;
    ui_rpmbaja5 = NULL;
    ui_rpmbaja6 = NULL;
    ui_rpmbaja7 = NULL;
    ui_tiraledsrpmcontainer = NULL;
    ui_led0 = NULL;
    ui_led1 = NULL;
    ui_led2 = NULL;
    ui_led3 = NULL;
    ui_led4 = NULL;
    ui_led5 = NULL;
    ui_led6 = NULL;
    ui_led7 = NULL;
    ui_led8 = NULL;
    ui_led9 = NULL;
    ui_led10 = NULL;
    ui_led11 = NULL;
    ui_led12 = NULL;
    ui_led13 = NULL;
    ui_led14 = NULL;
    ui_barrpm = NULL;
    ui_rpma = NULL;
    ui_rpmb = NULL;
    ui_rpmname = NULL;
    ui_rpm = NULL;
    ui_oiltpanel = NULL;
    ui_oilt = NULL;
    ui_oiltname = NULL;
    ui_oiltseparator = NULL;
    ui_oilppanel = NULL;
    ui_oilp = NULL;
    ui_oilpseparator = NULL;
    ui_oilpname = NULL;
    ui_fuelppanel = NULL;
    ui_fuelp = NULL;
    ui_fuelpseparator = NULL;
    ui_fuelpname = NULL;
    ui_lambdapanel = NULL;
    ui_lambda = NULL;
    ui_lambdaname = NULL;
    ui_lambdaseparator = NULL;
    ui_watertpanel = NULL;
    ui_watert = NULL;
    ui_watertseparator = NULL;
    ui_watertname = NULL;
    ui_sdownpanel = NULL;
    ui_sdownname = NULL;
    ui_sdown = NULL;
    ui_sdownseparator = NULL;
    ui_vbatpanel = NULL;
    ui_vbat = NULL;
    ui_vbatseparator = NULL;
    ui_vbatname = NULL;
    ui_fanpanel = NULL;
    ui_fanname = NULL;
    ui_fan = NULL;
    ui_fanseparator = NULL;
    ui_neutralpanel = NULL;
    ui_neutral = NULL;
    ui_warmuppanel = NULL;
    ui_warmup = NULL;
    ui_botonshowajustes = NULL;
    ui_ajustesboton = NULL;
    ui_ajustesnombre = NULL;

}
