// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: G26_v3

#include "../../include/ui/ui.h"


const ui_theme_variable_t _ui_theme_color_fondo[3] = {0x232323, 0x232323, 0xE9E9E9};
const ui_theme_variable_t _ui_theme_alpha_fondo[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_texto[3] = {0xD2D2D2, 0xD2D2D2, 0x202020};
const ui_theme_variable_t _ui_theme_alpha_texto[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_fbarra[3] = {0x3A3A3A, 0x3A3A3A, 0xAAAAAA};
const ui_theme_variable_t _ui_theme_alpha_fbarra[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_barrar[3] = {0x422727, 0x422727, 0xBC5C5C};
const ui_theme_variable_t _ui_theme_alpha_barrar[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_OSCURO;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

