// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../../include/ui/ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_fueltitlepanel = NULL;
lv_obj_t * ui_fuellabeltitle = NULL;
lv_obj_t * ui_PanelLambda = NULL;
lv_obj_t * ui_lambda = NULL;
lv_obj_t * ui_LambdaLabel = NULL;
lv_obj_t * ui_PanelLambdatarget = NULL;
lv_obj_t * ui_lambdatarget = NULL;
lv_obj_t * ui_LambdaLabel1 = NULL;
lv_obj_t * ui_Panelfuel = NULL;
lv_obj_t * ui_FUELLabel = NULL;
lv_obj_t * ui_fuel = NULL;
lv_obj_t * ui_PaneLCorrlamb = NULL;
lv_obj_t * ui_CORRLAMBDALabel1 = NULL;
lv_obj_t * ui_correctionlambda = NULL;
lv_obj_t * ui_PanelETC2 = NULL;
lv_obj_t * ui_ect2 = NULL;
lv_obj_t * ui_ECTlabel2 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fueltitlepanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_fueltitlepanel, 770);
    lv_obj_set_height(ui_fueltitlepanel, 63);
    lv_obj_set_x(ui_fueltitlepanel, -2);
    lv_obj_set_y(ui_fueltitlepanel, -202);
    lv_obj_set_align(ui_fueltitlepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fueltitlepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fuellabeltitle = lv_label_create(ui_fueltitlepanel);
    lv_obj_set_width(ui_fuellabeltitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuellabeltitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuellabeltitle, 9);
    lv_obj_set_y(ui_fuellabeltitle, 0);
    lv_obj_set_align(ui_fuellabeltitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuellabeltitle, "WARM UP");
    lv_obj_set_style_text_letter_space(ui_fuellabeltitle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_fuellabeltitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuellabeltitle, &ui_font_Consolas60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLambda = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelLambda, 379);
    lv_obj_set_height(ui_PanelLambda, 128);
    lv_obj_set_x(ui_PanelLambda, -195);
    lv_obj_set_y(ui_PanelLambda, -95);
    lv_obj_set_align(ui_PanelLambda, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLambda, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lambda = lv_label_create(ui_PanelLambda);
    lv_obj_set_width(ui_lambda, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lambda, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lambda, 55);
    lv_obj_set_y(ui_lambda, 0);
    lv_obj_set_align(ui_lambda, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lambda, "0.923");
    lv_obj_set_style_text_font(ui_lambda, &ui_font_Consolas60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LambdaLabel = lv_label_create(ui_PanelLambda);
    lv_obj_set_width(ui_LambdaLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LambdaLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LambdaLabel, -120);
    lv_obj_set_y(ui_LambdaLabel, -2);
    lv_obj_set_align(ui_LambdaLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LambdaLabel, "LAMBDA");
    lv_obj_set_style_text_color(ui_LambdaLabel, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LambdaLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LambdaLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLambdatarget = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelLambdatarget, 373);
    lv_obj_set_height(ui_PanelLambdatarget, 128);
    lv_obj_set_x(ui_PanelLambdatarget, 197);
    lv_obj_set_y(ui_PanelLambdatarget, -94);
    lv_obj_set_align(ui_PanelLambdatarget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLambdatarget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lambdatarget = lv_label_create(ui_PanelLambdatarget);
    lv_obj_set_width(ui_lambdatarget, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lambdatarget, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lambdatarget, 71);
    lv_obj_set_y(ui_lambdatarget, -1);
    lv_obj_set_align(ui_lambdatarget, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lambdatarget, "1.042");
    lv_obj_set_style_text_font(ui_lambdatarget, &ui_font_Consolas60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LambdaLabel1 = lv_label_create(ui_PanelLambdatarget);
    lv_obj_set_width(ui_LambdaLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LambdaLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LambdaLabel1, -109);
    lv_obj_set_y(ui_LambdaLabel1, -1);
    lv_obj_set_align(ui_LambdaLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LambdaLabel1, "LAMBDA TG");
    lv_obj_set_style_text_color(ui_LambdaLabel1, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LambdaLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LambdaLabel1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelfuel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panelfuel, 373);
    lv_obj_set_height(ui_Panelfuel, 52);
    lv_obj_set_x(ui_Panelfuel, 198);
    lv_obj_set_y(ui_Panelfuel, 72);
    lv_obj_set_align(ui_Panelfuel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelfuel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FUELLabel = lv_label_create(ui_Panelfuel);
    lv_obj_set_width(ui_FUELLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUELLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUELLabel, -127);
    lv_obj_set_y(ui_FUELLabel, 1);
    lv_obj_set_align(ui_FUELLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FUELLabel, "FUEL %");
    lv_obj_set_style_text_color(ui_FUELLabel, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FUELLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FUELLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuel = lv_label_create(ui_Panelfuel);
    lv_obj_set_width(ui_fuel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuel, 119);
    lv_obj_set_y(ui_fuel, -1);
    lv_obj_set_align(ui_fuel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuel, "28.4");
    lv_obj_set_style_text_font(ui_fuel, &ui_font_Consolas35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PaneLCorrlamb = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PaneLCorrlamb, 374);
    lv_obj_set_height(ui_PaneLCorrlamb, 52);
    lv_obj_set_x(ui_PaneLCorrlamb, 198);
    lv_obj_set_y(ui_PaneLCorrlamb, 7);
    lv_obj_set_align(ui_PaneLCorrlamb, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PaneLCorrlamb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CORRLAMBDALabel1 = lv_label_create(ui_PaneLCorrlamb);
    lv_obj_set_width(ui_CORRLAMBDALabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CORRLAMBDALabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CORRLAMBDALabel1, -94);
    lv_obj_set_y(ui_CORRLAMBDALabel1, 0);
    lv_obj_set_align(ui_CORRLAMBDALabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CORRLAMBDALabel1, "LAMBDA CORR %");
    lv_obj_set_style_text_color(ui_CORRLAMBDALabel1, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CORRLAMBDALabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CORRLAMBDALabel1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_correctionlambda = lv_label_create(ui_PaneLCorrlamb);
    lv_obj_set_width(ui_correctionlambda, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_correctionlambda, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_correctionlambda, 119);
    lv_obj_set_y(ui_correctionlambda, -1);
    lv_obj_set_align(ui_correctionlambda, LV_ALIGN_CENTER);
    lv_label_set_text(ui_correctionlambda, "4.75");
    lv_obj_set_style_text_font(ui_correctionlambda, &ui_font_Consolas35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelETC2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelETC2, 377);
    lv_obj_set_height(ui_PanelETC2, 128);
    lv_obj_set_x(ui_PanelETC2, -195);
    lv_obj_set_y(ui_PanelETC2, 42);
    lv_obj_set_align(ui_PanelETC2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelETC2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ect2 = lv_label_create(ui_PanelETC2);
    lv_obj_set_width(ui_ect2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ect2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ect2, 100);
    lv_obj_set_y(ui_ect2, -2);
    lv_obj_set_align(ui_ect2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ect2, "80");
    lv_obj_set_style_text_font(ui_ect2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ECTlabel2 = lv_label_create(ui_PanelETC2);
    lv_obj_set_width(ui_ECTlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ECTlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ECTlabel2, -142);
    lv_obj_set_y(ui_ECTlabel2, 0);
    lv_obj_set_align(ui_ECTlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ECTlabel2, "ECT");
    lv_obj_set_style_text_color(ui_ECTlabel2, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ECTlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ECTlabel2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_fueltitlepanel = NULL;
    ui_fuellabeltitle = NULL;
    ui_PanelLambda = NULL;
    ui_lambda = NULL;
    ui_LambdaLabel = NULL;
    ui_PanelLambdatarget = NULL;
    ui_lambdatarget = NULL;
    ui_LambdaLabel1 = NULL;
    ui_Panelfuel = NULL;
    ui_FUELLabel = NULL;
    ui_fuel = NULL;
    ui_PaneLCorrlamb = NULL;
    ui_CORRLAMBDALabel1 = NULL;
    ui_correctionlambda = NULL;
    ui_PanelETC2 = NULL;
    ui_ect2 = NULL;
    ui_ECTlabel2 = NULL;

}
