// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../../include/ui/ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_fueltitlepanel2 = NULL;
lv_obj_t * ui_fuellabeltitle2 = NULL;
lv_obj_t * ui_PanelAUX1 = NULL;
lv_obj_t * ui_AUXLabel1 = NULL;
lv_obj_t * ui_auxstatus1 = NULL;
lv_obj_t * ui_PanelAUX2 = NULL;
lv_obj_t * ui_AUXLabel2 = NULL;
lv_obj_t * ui_auxstatus2 = NULL;
lv_obj_t * ui_PanelAUX3 = NULL;
lv_obj_t * ui_AUXLabel3 = NULL;
lv_obj_t * ui_auxstatus3 = NULL;
lv_obj_t * ui_PanelAUX4 = NULL;
lv_obj_t * ui_AUXLabel4 = NULL;
lv_obj_t * ui_auxstatus4 = NULL;
lv_obj_t * ui_PanelAUX5 = NULL;
lv_obj_t * ui_AUXLabel5 = NULL;
lv_obj_t * ui_auxstatus5 = NULL;
lv_obj_t * ui_PanelAUX6 = NULL;
lv_obj_t * ui_AUXLabel6 = NULL;
lv_obj_t * ui_auxstatus6 = NULL;
lv_obj_t * ui_PanelAUX7 = NULL;
lv_obj_t * ui_AUXLabel7 = NULL;
lv_obj_t * ui_auxstatus7 = NULL;
lv_obj_t * ui_PanelAUX8 = NULL;
lv_obj_t * ui_AUXLabel8 = NULL;
lv_obj_t * ui_auxstatus8 = NULL;
lv_obj_t * ui_PanelAUX9 = NULL;
lv_obj_t * ui_AUXLabel9 = NULL;
lv_obj_t * ui_auxstatus9 = NULL;
lv_obj_t * ui_PanelAUX10 = NULL;
lv_obj_t * ui_AUXLabel10 = NULL;
lv_obj_t * ui_auxstatus10 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fueltitlepanel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_fueltitlepanel2, 770);
    lv_obj_set_height(ui_fueltitlepanel2, 63);
    lv_obj_set_x(ui_fueltitlepanel2, -2);
    lv_obj_set_y(ui_fueltitlepanel2, -202);
    lv_obj_set_align(ui_fueltitlepanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fueltitlepanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fuellabeltitle2 = lv_label_create(ui_fueltitlepanel2);
    lv_obj_set_width(ui_fuellabeltitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuellabeltitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuellabeltitle2, 2);
    lv_obj_set_y(ui_fuellabeltitle2, 1);
    lv_obj_set_align(ui_fuellabeltitle2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuellabeltitle2, "AUX");
    lv_obj_set_style_text_letter_space(ui_fuellabeltitle2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_fuellabeltitle2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuellabeltitle2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX1, 378);
    lv_obj_set_height(ui_PanelAUX1, 52);
    lv_obj_set_x(ui_PanelAUX1, -197);
    lv_obj_set_y(ui_PanelAUX1, -133);
    lv_obj_set_align(ui_PanelAUX1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel1 = lv_label_create(ui_PanelAUX1);
    lv_obj_set_width(ui_AUXLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel1, -108);
    lv_obj_set_y(ui_AUXLabel1, 1);
    lv_obj_set_align(ui_AUXLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel1, "AUX 1 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel1, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus1 = lv_label_create(ui_PanelAUX1);
    lv_obj_set_width(ui_auxstatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus1, 117);
    lv_obj_set_y(ui_auxstatus1, 0);
    lv_obj_set_align(ui_auxstatus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus1, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX2, 378);
    lv_obj_set_height(ui_PanelAUX2, 52);
    lv_obj_set_x(ui_PanelAUX2, -196);
    lv_obj_set_y(ui_PanelAUX2, -70);
    lv_obj_set_align(ui_PanelAUX2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel2 = lv_label_create(ui_PanelAUX2);
    lv_obj_set_width(ui_AUXLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel2, -108);
    lv_obj_set_y(ui_AUXLabel2, 1);
    lv_obj_set_align(ui_AUXLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel2, "AUX 2 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel2, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus2 = lv_label_create(ui_PanelAUX2);
    lv_obj_set_width(ui_auxstatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus2, 117);
    lv_obj_set_y(ui_auxstatus2, 0);
    lv_obj_set_align(ui_auxstatus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus2, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX3 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX3, 378);
    lv_obj_set_height(ui_PanelAUX3, 52);
    lv_obj_set_x(ui_PanelAUX3, -196);
    lv_obj_set_y(ui_PanelAUX3, -6);
    lv_obj_set_align(ui_PanelAUX3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel3 = lv_label_create(ui_PanelAUX3);
    lv_obj_set_width(ui_AUXLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel3, -108);
    lv_obj_set_y(ui_AUXLabel3, 1);
    lv_obj_set_align(ui_AUXLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel3, "AUX 3 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel3, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus3 = lv_label_create(ui_PanelAUX3);
    lv_obj_set_width(ui_auxstatus3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus3, 117);
    lv_obj_set_y(ui_auxstatus3, 0);
    lv_obj_set_align(ui_auxstatus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus3, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX4 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX4, 378);
    lv_obj_set_height(ui_PanelAUX4, 52);
    lv_obj_set_x(ui_PanelAUX4, -195);
    lv_obj_set_y(ui_PanelAUX4, 57);
    lv_obj_set_align(ui_PanelAUX4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel4 = lv_label_create(ui_PanelAUX4);
    lv_obj_set_width(ui_AUXLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel4, -108);
    lv_obj_set_y(ui_AUXLabel4, 1);
    lv_obj_set_align(ui_AUXLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel4, "AUX 4 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel4, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus4 = lv_label_create(ui_PanelAUX4);
    lv_obj_set_width(ui_auxstatus4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus4, 117);
    lv_obj_set_y(ui_auxstatus4, 0);
    lv_obj_set_align(ui_auxstatus4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus4, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX5 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX5, 378);
    lv_obj_set_height(ui_PanelAUX5, 52);
    lv_obj_set_x(ui_PanelAUX5, -195);
    lv_obj_set_y(ui_PanelAUX5, 120);
    lv_obj_set_align(ui_PanelAUX5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel5 = lv_label_create(ui_PanelAUX5);
    lv_obj_set_width(ui_AUXLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel5, -108);
    lv_obj_set_y(ui_AUXLabel5, 1);
    lv_obj_set_align(ui_AUXLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel5, "AUX 5 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel5, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus5 = lv_label_create(ui_PanelAUX5);
    lv_obj_set_width(ui_auxstatus5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus5, 117);
    lv_obj_set_y(ui_auxstatus5, 0);
    lv_obj_set_align(ui_auxstatus5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus5, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX6 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX6, 378);
    lv_obj_set_height(ui_PanelAUX6, 52);
    lv_obj_set_x(ui_PanelAUX6, 193);
    lv_obj_set_y(ui_PanelAUX6, -133);
    lv_obj_set_align(ui_PanelAUX6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel6 = lv_label_create(ui_PanelAUX6);
    lv_obj_set_width(ui_AUXLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel6, -108);
    lv_obj_set_y(ui_AUXLabel6, 1);
    lv_obj_set_align(ui_AUXLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel6, "AUX 6 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel6, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus6 = lv_label_create(ui_PanelAUX6);
    lv_obj_set_width(ui_auxstatus6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus6, 117);
    lv_obj_set_y(ui_auxstatus6, 0);
    lv_obj_set_align(ui_auxstatus6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus6, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX7 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX7, 378);
    lv_obj_set_height(ui_PanelAUX7, 52);
    lv_obj_set_x(ui_PanelAUX7, 194);
    lv_obj_set_y(ui_PanelAUX7, -70);
    lv_obj_set_align(ui_PanelAUX7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel7 = lv_label_create(ui_PanelAUX7);
    lv_obj_set_width(ui_AUXLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel7, -108);
    lv_obj_set_y(ui_AUXLabel7, 1);
    lv_obj_set_align(ui_AUXLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel7, "AUX 7 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel7, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus7 = lv_label_create(ui_PanelAUX7);
    lv_obj_set_width(ui_auxstatus7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus7, 117);
    lv_obj_set_y(ui_auxstatus7, 0);
    lv_obj_set_align(ui_auxstatus7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus7, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX8 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX8, 378);
    lv_obj_set_height(ui_PanelAUX8, 52);
    lv_obj_set_x(ui_PanelAUX8, 193);
    lv_obj_set_y(ui_PanelAUX8, -6);
    lv_obj_set_align(ui_PanelAUX8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel8 = lv_label_create(ui_PanelAUX8);
    lv_obj_set_width(ui_AUXLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel8, -108);
    lv_obj_set_y(ui_AUXLabel8, 1);
    lv_obj_set_align(ui_AUXLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel8, "AUX 8 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel8, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus8 = lv_label_create(ui_PanelAUX8);
    lv_obj_set_width(ui_auxstatus8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus8, 117);
    lv_obj_set_y(ui_auxstatus8, 0);
    lv_obj_set_align(ui_auxstatus8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus8, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX9 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX9, 378);
    lv_obj_set_height(ui_PanelAUX9, 52);
    lv_obj_set_x(ui_PanelAUX9, 194);
    lv_obj_set_y(ui_PanelAUX9, 57);
    lv_obj_set_align(ui_PanelAUX9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel9 = lv_label_create(ui_PanelAUX9);
    lv_obj_set_width(ui_AUXLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel9, -108);
    lv_obj_set_y(ui_AUXLabel9, 1);
    lv_obj_set_align(ui_AUXLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel9, "AUX 9 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel9, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus9 = lv_label_create(ui_PanelAUX9);
    lv_obj_set_width(ui_auxstatus9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus9, 117);
    lv_obj_set_y(ui_auxstatus9, 0);
    lv_obj_set_align(ui_auxstatus9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus9, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAUX10 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelAUX10, 378);
    lv_obj_set_height(ui_PanelAUX10, 52);
    lv_obj_set_x(ui_PanelAUX10, 193);
    lv_obj_set_y(ui_PanelAUX10, 120);
    lv_obj_set_align(ui_PanelAUX10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelAUX10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AUXLabel10 = lv_label_create(ui_PanelAUX10);
    lv_obj_set_width(ui_AUXLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUXLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUXLabel10, -108);
    lv_obj_set_y(ui_AUXLabel10, 1);
    lv_obj_set_align(ui_AUXLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AUXLabel10, "AUX 10 STATUS");
    lv_obj_set_style_text_color(ui_AUXLabel10, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUXLabel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUXLabel10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auxstatus10 = lv_label_create(ui_PanelAUX10);
    lv_obj_set_width(ui_auxstatus10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auxstatus10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auxstatus10, 117);
    lv_obj_set_y(ui_auxstatus10, 0);
    lv_obj_set_align(ui_auxstatus10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auxstatus10, "OFF");
    lv_obj_set_style_text_font(ui_auxstatus10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_fueltitlepanel2 = NULL;
    ui_fuellabeltitle2 = NULL;
    ui_PanelAUX1 = NULL;
    ui_AUXLabel1 = NULL;
    ui_auxstatus1 = NULL;
    ui_PanelAUX2 = NULL;
    ui_AUXLabel2 = NULL;
    ui_auxstatus2 = NULL;
    ui_PanelAUX3 = NULL;
    ui_AUXLabel3 = NULL;
    ui_auxstatus3 = NULL;
    ui_PanelAUX4 = NULL;
    ui_AUXLabel4 = NULL;
    ui_auxstatus4 = NULL;
    ui_PanelAUX5 = NULL;
    ui_AUXLabel5 = NULL;
    ui_auxstatus5 = NULL;
    ui_PanelAUX6 = NULL;
    ui_AUXLabel6 = NULL;
    ui_auxstatus6 = NULL;
    ui_PanelAUX7 = NULL;
    ui_AUXLabel7 = NULL;
    ui_auxstatus7 = NULL;
    ui_PanelAUX8 = NULL;
    ui_AUXLabel8 = NULL;
    ui_auxstatus8 = NULL;
    ui_PanelAUX9 = NULL;
    ui_AUXLabel9 = NULL;
    ui_auxstatus9 = NULL;
    ui_PanelAUX10 = NULL;
    ui_AUXLabel10 = NULL;
    ui_auxstatus10 = NULL;

}
