// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../../include/ui/ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_PanelGear = NULL;
lv_obj_t * ui_gear = NULL;
lv_obj_t * ui_PanelRPM = NULL;
lv_obj_t * ui_rpm = NULL;
lv_obj_t * ui_PanelBATT = NULL;
lv_obj_t * ui_battvoltlabel = NULL;
lv_obj_t * ui_battvolt = NULL;
lv_obj_t * ui_PanelETC = NULL;
lv_obj_t * ui_ect = NULL;
lv_obj_t * ui_ECTlabel = NULL;
lv_obj_t * ui_PanelSHUTDOWN = NULL;
lv_obj_t * ui_SHUTDOWN_LABEL = NULL;
lv_obj_t * ui_shutdown = NULL;
lv_obj_t * ui_PanelFAN = NULL;
lv_obj_t * ui_FANLabel = NULL;
lv_obj_t * ui_fan = NULL;

// RPM LED Bar - 16 mini panels
lv_obj_t * ui_RPMBar1 = NULL;
lv_obj_t * ui_RPMBar2 = NULL;
lv_obj_t * ui_RPMBar3 = NULL;
lv_obj_t * ui_RPMBar4 = NULL;
lv_obj_t * ui_RPMBar5 = NULL;
lv_obj_t * ui_RPMBar6 = NULL;
lv_obj_t * ui_RPMBar7 = NULL;
lv_obj_t * ui_RPMBar8 = NULL;
lv_obj_t * ui_RPMBar9 = NULL;
lv_obj_t * ui_RPMBar10 = NULL;
lv_obj_t * ui_RPMBar11 = NULL;
lv_obj_t * ui_RPMBar12 = NULL;
lv_obj_t * ui_RPMBar13 = NULL;
lv_obj_t * ui_RPMBar14 = NULL;
lv_obj_t * ui_RPMBar15 = NULL;
lv_obj_t * ui_RPMBar16 = NULL;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Create 16 RPM LED Bar panels across the top (8000-12500 RPM range)
    // Each panel is 50px wide (800/16), 40px high, positioned at top
    
    ui_RPMBar1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar1, 48);   // 50px - 2px margin
    lv_obj_set_height(ui_RPMBar1, 35);
    lv_obj_set_x(ui_RPMBar1, -375);     // Starting from left: -400 + 25
    lv_obj_set_y(ui_RPMBar1, -220);
    lv_obj_set_align(ui_RPMBar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar1, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar2, 48);
    lv_obj_set_height(ui_RPMBar2, 35);
    lv_obj_set_x(ui_RPMBar2, -325);
    lv_obj_set_y(ui_RPMBar2, -220);
    lv_obj_set_align(ui_RPMBar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar2, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar3, 48);
    lv_obj_set_height(ui_RPMBar3, 35);
    lv_obj_set_x(ui_RPMBar3, -275);
    lv_obj_set_y(ui_RPMBar3, -220);
    lv_obj_set_align(ui_RPMBar3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar3, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar4, 48);
    lv_obj_set_height(ui_RPMBar4, 35);
    lv_obj_set_x(ui_RPMBar4, -225);
    lv_obj_set_y(ui_RPMBar4, -220);
    lv_obj_set_align(ui_RPMBar4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar4, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar5, 48);
    lv_obj_set_height(ui_RPMBar5, 35);
    lv_obj_set_x(ui_RPMBar5, -175);
    lv_obj_set_y(ui_RPMBar5, -220);
    lv_obj_set_align(ui_RPMBar5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar5, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar6, 48);
    lv_obj_set_height(ui_RPMBar6, 35);
    lv_obj_set_x(ui_RPMBar6, -125);
    lv_obj_set_y(ui_RPMBar6, -220);
    lv_obj_set_align(ui_RPMBar6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar6, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar7, 48);
    lv_obj_set_height(ui_RPMBar7, 35);
    lv_obj_set_x(ui_RPMBar7, -75);
    lv_obj_set_y(ui_RPMBar7, -220);
    lv_obj_set_align(ui_RPMBar7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar7, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar8, 48);
    lv_obj_set_height(ui_RPMBar8, 35);
    lv_obj_set_x(ui_RPMBar8, -25);
    lv_obj_set_y(ui_RPMBar8, -220);
    lv_obj_set_align(ui_RPMBar8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar8, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar9 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar9, 48);
    lv_obj_set_height(ui_RPMBar9, 35);
    lv_obj_set_x(ui_RPMBar9, 25);
    lv_obj_set_y(ui_RPMBar9, -220);
    lv_obj_set_align(ui_RPMBar9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar9, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar10, 48);
    lv_obj_set_height(ui_RPMBar10, 35);
    lv_obj_set_x(ui_RPMBar10, 75);
    lv_obj_set_y(ui_RPMBar10, -220);
    lv_obj_set_align(ui_RPMBar10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar10, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar11, 48);
    lv_obj_set_height(ui_RPMBar11, 35);
    lv_obj_set_x(ui_RPMBar11, 125);
    lv_obj_set_y(ui_RPMBar11, -220);
    lv_obj_set_align(ui_RPMBar11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar11, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar12 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar12, 48);
    lv_obj_set_height(ui_RPMBar12, 35);
    lv_obj_set_x(ui_RPMBar12, 175);
    lv_obj_set_y(ui_RPMBar12, -220);
    lv_obj_set_align(ui_RPMBar12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar12, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar13 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar13, 48);
    lv_obj_set_height(ui_RPMBar13, 35);
    lv_obj_set_x(ui_RPMBar13, 225);
    lv_obj_set_y(ui_RPMBar13, -220);
    lv_obj_set_align(ui_RPMBar13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar13, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar14 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar14, 48);
    lv_obj_set_height(ui_RPMBar14, 35);
    lv_obj_set_x(ui_RPMBar14, 275);
    lv_obj_set_y(ui_RPMBar14, -220);
    lv_obj_set_align(ui_RPMBar14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar14, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar15 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar15, 48);
    lv_obj_set_height(ui_RPMBar15, 35);
    lv_obj_set_x(ui_RPMBar15, 325);
    lv_obj_set_y(ui_RPMBar15, -220);
    lv_obj_set_align(ui_RPMBar15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar15, LV_OBJ_FLAG_SCROLLABLE);

    ui_RPMBar16 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RPMBar16, 48);
    lv_obj_set_height(ui_RPMBar16, 35);
    lv_obj_set_x(ui_RPMBar16, 375);
    lv_obj_set_y(ui_RPMBar16, -220);
    lv_obj_set_align(ui_RPMBar16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar16, LV_OBJ_FLAG_SCROLLABLE);

    ui_PanelGear = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelGear, 229);
    lv_obj_set_height(ui_PanelGear, 290);
    lv_obj_set_x(ui_PanelGear, 0);
    lv_obj_set_y(ui_PanelGear, 91);  // Moved down from 41
    lv_obj_set_align(ui_PanelGear, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelGear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gear = lv_label_create(ui_PanelGear);
    lv_obj_set_width(ui_gear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gear, 2);
    lv_obj_set_y(ui_gear, 6);
    lv_obj_set_align(ui_gear, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_gear, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_gear, "N");
    lv_obj_set_style_text_color(ui_gear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_gear, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gear, &ui_font_Consolas350, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRPM = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelRPM, 778);
    lv_obj_set_height(ui_PanelRPM, 126);
    lv_obj_set_x(ui_PanelRPM, 0);
    lv_obj_set_y(ui_PanelRPM, -133);  // Moved down from -173
    lv_obj_set_align(ui_PanelRPM, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelRPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rpm = lv_label_create(ui_PanelRPM);
    lv_obj_set_width(ui_rpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm, -2);
    lv_obj_set_y(ui_rpm, 3);
    lv_obj_set_align(ui_rpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm, "12800");
    lv_obj_set_style_text_letter_space(ui_rpm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm, &ui_font_Consolas150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBATT = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelBATT, 258);
    lv_obj_set_height(ui_PanelBATT, 130);
    lv_obj_set_x(ui_PanelBATT, -255);
    lv_obj_set_y(ui_PanelBATT, 13);  // Moved down from -37
    lv_obj_set_align(ui_PanelBATT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBATT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battvoltlabel = lv_label_create(ui_PanelBATT);
    lv_obj_set_width(ui_battvoltlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battvoltlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battvoltlabel, -88);
    lv_obj_set_y(ui_battvoltlabel, 1);
    lv_obj_set_align(ui_battvoltlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battvoltlabel, "VBATT");
    lv_obj_set_style_text_color(ui_battvoltlabel, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_battvoltlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_battvoltlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battvolt = lv_label_create(ui_PanelBATT);
    lv_obj_set_width(ui_battvolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battvolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battvolt, 34);
    lv_obj_set_y(ui_battvolt, 2);
    lv_obj_set_align(ui_battvolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battvolt, "13.64");
    lv_obj_set_style_text_font(ui_battvolt, &ui_font_Consolas60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelETC = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelETC, 258);
    lv_obj_set_height(ui_PanelETC, 128);
    lv_obj_set_x(ui_PanelETC, 254);
    lv_obj_set_y(ui_PanelETC, 12);  // Moved down from -38
    lv_obj_set_align(ui_PanelETC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelETC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ect = lv_label_create(ui_PanelETC);
    lv_obj_set_width(ui_ect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ect, 58);
    lv_obj_set_y(ui_ect, 3);
    lv_obj_set_align(ui_ect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ect, "80");
    lv_obj_set_style_text_font(ui_ect, &ui_font_Consolas60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ECTlabel = lv_label_create(ui_PanelETC);
    lv_obj_set_width(ui_ECTlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ECTlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ECTlabel, -94);
    lv_obj_set_y(ui_ECTlabel, 1);
    lv_obj_set_align(ui_ECTlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ECTlabel, "ECT");
    lv_obj_set_style_text_color(ui_ECTlabel, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ECTlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ECTlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSHUTDOWN = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelSHUTDOWN, 259);
    lv_obj_set_height(ui_PanelSHUTDOWN, 52);
    lv_obj_set_x(ui_PanelSHUTDOWN, -256);
    lv_obj_set_y(ui_PanelSHUTDOWN, 113);  // Moved down from 63
    lv_obj_set_align(ui_PanelSHUTDOWN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSHUTDOWN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SHUTDOWN_LABEL = lv_label_create(ui_PanelSHUTDOWN);
    lv_obj_set_width(ui_SHUTDOWN_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SHUTDOWN_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SHUTDOWN_LABEL, -67);
    lv_obj_set_y(ui_SHUTDOWN_LABEL, -1);
    lv_obj_set_align(ui_SHUTDOWN_LABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SHUTDOWN_LABEL, "SHUTDOWN");
    lv_obj_set_style_text_color(ui_SHUTDOWN_LABEL, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SHUTDOWN_LABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SHUTDOWN_LABEL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shutdown = lv_label_create(ui_PanelSHUTDOWN);
    lv_obj_set_width(ui_shutdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shutdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shutdown, 72);
    lv_obj_set_y(ui_shutdown, 0);
    lv_obj_set_align(ui_shutdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shutdown, "OFF");
    lv_obj_set_style_text_font(ui_shutdown, &ui_font_Consolas35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFAN = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelFAN, 255);
    lv_obj_set_height(ui_PanelFAN, 52);
    lv_obj_set_x(ui_PanelFAN, 254);
    lv_obj_set_y(ui_PanelFAN, 111);  // Moved down from 61
    lv_obj_set_align(ui_PanelFAN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FANLabel = lv_label_create(ui_PanelFAN);
    lv_obj_set_width(ui_FANLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FANLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FANLabel, -91);
    lv_obj_set_y(ui_FANLabel, 9);
    lv_obj_set_align(ui_FANLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FANLabel, "FAN\n");
    lv_obj_set_style_text_color(ui_FANLabel, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FANLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FANLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fan = lv_label_create(ui_PanelFAN);
    lv_obj_set_width(ui_fan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan, 58);
    lv_obj_set_y(ui_fan, -1);
    lv_obj_set_align(ui_fan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fan, "OFF");
    lv_obj_set_style_text_font(ui_fan, &ui_font_Consolas35, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_PanelGear = NULL;
    ui_gear = NULL;
    ui_PanelRPM = NULL;
    ui_rpm = NULL;
    ui_PanelBATT = NULL;
    ui_battvoltlabel = NULL;
    ui_battvolt = NULL;
    ui_PanelETC = NULL;
    ui_ect = NULL;
    ui_ECTlabel = NULL;
    ui_PanelSHUTDOWN = NULL;
    ui_SHUTDOWN_LABEL = NULL;
    ui_shutdown = NULL;
    ui_PanelFAN = NULL;
    ui_FANLabel = NULL;
    ui_fan = NULL;
    
    // RPM Bar panels
    ui_RPMBar1 = NULL;
    ui_RPMBar2 = NULL;
    ui_RPMBar3 = NULL;
    ui_RPMBar4 = NULL;
    ui_RPMBar5 = NULL;
    ui_RPMBar6 = NULL;
    ui_RPMBar7 = NULL;
    ui_RPMBar8 = NULL;
    ui_RPMBar9 = NULL;
    ui_RPMBar10 = NULL;
    ui_RPMBar11 = NULL;
    ui_RPMBar12 = NULL;
    ui_RPMBar13 = NULL;
    ui_RPMBar14 = NULL;
    ui_RPMBar15 = NULL;
    ui_RPMBar16 = NULL;
}
