// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../../include/ui/ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_fueltitlepanel3 = NULL;
lv_obj_t * ui_fuellabeltitle3 = NULL;
lv_obj_t * ui_PanelDIGITAL1 = NULL;
lv_obj_t * ui_DIGITALLabel1 = NULL;
lv_obj_t * ui_digitalstatus1 = NULL;
lv_obj_t * ui_PanelDIGITAL2 = NULL;
lv_obj_t * ui_DIGITALLabel2 = NULL;
lv_obj_t * ui_digitalstatus2 = NULL;
lv_obj_t * ui_PanelDIGITAL3 = NULL;
lv_obj_t * ui_DIGITALLabel3 = NULL;
lv_obj_t * ui_digitalstatus3 = NULL;
lv_obj_t * ui_PanelDIGITAL4 = NULL;
lv_obj_t * ui_DIGITALLabel4 = NULL;
lv_obj_t * ui_digitalstatus4 = NULL;
lv_obj_t * ui_PanelDIGITAL5 = NULL;
lv_obj_t * ui_DIGITALLabel5 = NULL;
lv_obj_t * ui_digitalstatus5 = NULL;
lv_obj_t * ui_PanelDIGITAL6 = NULL;
lv_obj_t * ui_DIGITALLabel6 = NULL;
lv_obj_t * ui_digitalstatus6 = NULL;
lv_obj_t * ui_PanelDIGITAL7 = NULL;
lv_obj_t * ui_DIGITALLabel7 = NULL;
lv_obj_t * ui_digitalstatus7 = NULL;
lv_obj_t * ui_PanelDIGITAL8 = NULL;
lv_obj_t * ui_DIGITALLabel8 = NULL;
lv_obj_t * ui_digitalstatus8 = NULL;
lv_obj_t * ui_PanelDIGITAL9 = NULL;
lv_obj_t * ui_DIGITALLabel9 = NULL;
lv_obj_t * ui_digitalstatus9 = NULL;
lv_obj_t * ui_PanelDIGITAL10 = NULL;
lv_obj_t * ui_DIGITALLabel10 = NULL;
lv_obj_t * ui_digitalstatus10 = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fueltitlepanel3 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_fueltitlepanel3, 770);
    lv_obj_set_height(ui_fueltitlepanel3, 63);
    lv_obj_set_x(ui_fueltitlepanel3, -2);
    lv_obj_set_y(ui_fueltitlepanel3, -202);
    lv_obj_set_align(ui_fueltitlepanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fueltitlepanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fuellabeltitle3 = lv_label_create(ui_fueltitlepanel3);
    lv_obj_set_width(ui_fuellabeltitle3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuellabeltitle3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuellabeltitle3, 2);
    lv_obj_set_y(ui_fuellabeltitle3, 1);
    lv_obj_set_align(ui_fuellabeltitle3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuellabeltitle3, "DIGITAL");
    lv_obj_set_style_text_letter_space(ui_fuellabeltitle3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_fuellabeltitle3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuellabeltitle3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL1 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL1, 378);
    lv_obj_set_height(ui_PanelDIGITAL1, 52);
    lv_obj_set_x(ui_PanelDIGITAL1, -197);
    lv_obj_set_y(ui_PanelDIGITAL1, -133);
    lv_obj_set_align(ui_PanelDIGITAL1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel1 = lv_label_create(ui_PanelDIGITAL1);
    lv_obj_set_width(ui_DIGITALLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel1, -96);
    lv_obj_set_y(ui_DIGITALLabel1, 1);
    lv_obj_set_align(ui_DIGITALLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel1, "DIGITAL 1 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel1, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus1 = lv_label_create(ui_PanelDIGITAL1);
    lv_obj_set_width(ui_digitalstatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus1, 117);
    lv_obj_set_y(ui_digitalstatus1, 0);
    lv_obj_set_align(ui_digitalstatus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus1, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL2 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL2, 378);
    lv_obj_set_height(ui_PanelDIGITAL2, 52);
    lv_obj_set_x(ui_PanelDIGITAL2, -196);
    lv_obj_set_y(ui_PanelDIGITAL2, -68);
    lv_obj_set_align(ui_PanelDIGITAL2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel2 = lv_label_create(ui_PanelDIGITAL2);
    lv_obj_set_width(ui_DIGITALLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel2, -96);
    lv_obj_set_y(ui_DIGITALLabel2, 1);
    lv_obj_set_align(ui_DIGITALLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel2, "DIGITAL 2 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel2, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus2 = lv_label_create(ui_PanelDIGITAL2);
    lv_obj_set_width(ui_digitalstatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus2, 117);
    lv_obj_set_y(ui_digitalstatus2, 0);
    lv_obj_set_align(ui_digitalstatus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus2, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL3 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL3, 378);
    lv_obj_set_height(ui_PanelDIGITAL3, 52);
    lv_obj_set_x(ui_PanelDIGITAL3, -196);
    lv_obj_set_y(ui_PanelDIGITAL3, -3);
    lv_obj_set_align(ui_PanelDIGITAL3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel3 = lv_label_create(ui_PanelDIGITAL3);
    lv_obj_set_width(ui_DIGITALLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel3, -96);
    lv_obj_set_y(ui_DIGITALLabel3, 1);
    lv_obj_set_align(ui_DIGITALLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel3, "DIGITAL 3 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel3, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus3 = lv_label_create(ui_PanelDIGITAL3);
    lv_obj_set_width(ui_digitalstatus3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus3, 117);
    lv_obj_set_y(ui_digitalstatus3, 0);
    lv_obj_set_align(ui_digitalstatus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus3, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL4 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL4, 378);
    lv_obj_set_height(ui_PanelDIGITAL4, 52);
    lv_obj_set_x(ui_PanelDIGITAL4, -195);
    lv_obj_set_y(ui_PanelDIGITAL4, 60);
    lv_obj_set_align(ui_PanelDIGITAL4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel4 = lv_label_create(ui_PanelDIGITAL4);
    lv_obj_set_width(ui_DIGITALLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel4, -96);
    lv_obj_set_y(ui_DIGITALLabel4, 1);
    lv_obj_set_align(ui_DIGITALLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel4, "DIGITAL 4 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel4, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus4 = lv_label_create(ui_PanelDIGITAL4);
    lv_obj_set_width(ui_digitalstatus4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus4, 117);
    lv_obj_set_y(ui_digitalstatus4, 0);
    lv_obj_set_align(ui_digitalstatus4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus4, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL5 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL5, 378);
    lv_obj_set_height(ui_PanelDIGITAL5, 52);
    lv_obj_set_x(ui_PanelDIGITAL5, -195);
    lv_obj_set_y(ui_PanelDIGITAL5, 124);
    lv_obj_set_align(ui_PanelDIGITAL5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel5 = lv_label_create(ui_PanelDIGITAL5);
    lv_obj_set_width(ui_DIGITALLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel5, -96);
    lv_obj_set_y(ui_DIGITALLabel5, 1);
    lv_obj_set_align(ui_DIGITALLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel5, "DIGITAL 5 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel5, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus5 = lv_label_create(ui_PanelDIGITAL5);
    lv_obj_set_width(ui_digitalstatus5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus5, 117);
    lv_obj_set_y(ui_digitalstatus5, 0);
    lv_obj_set_align(ui_digitalstatus5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus5, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL6 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL6, 378);
    lv_obj_set_height(ui_PanelDIGITAL6, 52);
    lv_obj_set_x(ui_PanelDIGITAL6, 194);
    lv_obj_set_y(ui_PanelDIGITAL6, -133);
    lv_obj_set_align(ui_PanelDIGITAL6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel6 = lv_label_create(ui_PanelDIGITAL6);
    lv_obj_set_width(ui_DIGITALLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel6, -96);
    lv_obj_set_y(ui_DIGITALLabel6, 1);
    lv_obj_set_align(ui_DIGITALLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel6, "DIGITAL 6 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel6, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus6 = lv_label_create(ui_PanelDIGITAL6);
    lv_obj_set_width(ui_digitalstatus6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus6, 117);
    lv_obj_set_y(ui_digitalstatus6, 0);
    lv_obj_set_align(ui_digitalstatus6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus6, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL7 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL7, 378);
    lv_obj_set_height(ui_PanelDIGITAL7, 52);
    lv_obj_set_x(ui_PanelDIGITAL7, 193);
    lv_obj_set_y(ui_PanelDIGITAL7, -68);
    lv_obj_set_align(ui_PanelDIGITAL7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel7 = lv_label_create(ui_PanelDIGITAL7);
    lv_obj_set_width(ui_DIGITALLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel7, -96);
    lv_obj_set_y(ui_DIGITALLabel7, 1);
    lv_obj_set_align(ui_DIGITALLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel7, "DIGITAL 7 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel7, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus7 = lv_label_create(ui_PanelDIGITAL7);
    lv_obj_set_width(ui_digitalstatus7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus7, 117);
    lv_obj_set_y(ui_digitalstatus7, 0);
    lv_obj_set_align(ui_digitalstatus7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus7, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL8 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL8, 378);
    lv_obj_set_height(ui_PanelDIGITAL8, 52);
    lv_obj_set_x(ui_PanelDIGITAL8, 194);
    lv_obj_set_y(ui_PanelDIGITAL8, -3);
    lv_obj_set_align(ui_PanelDIGITAL8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel8 = lv_label_create(ui_PanelDIGITAL8);
    lv_obj_set_width(ui_DIGITALLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel8, -96);
    lv_obj_set_y(ui_DIGITALLabel8, 1);
    lv_obj_set_align(ui_DIGITALLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel8, "DIGITAL 8 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel8, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus8 = lv_label_create(ui_PanelDIGITAL8);
    lv_obj_set_width(ui_digitalstatus8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus8, 117);
    lv_obj_set_y(ui_digitalstatus8, 0);
    lv_obj_set_align(ui_digitalstatus8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus8, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL9 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL9, 378);
    lv_obj_set_height(ui_PanelDIGITAL9, 52);
    lv_obj_set_x(ui_PanelDIGITAL9, 194);
    lv_obj_set_y(ui_PanelDIGITAL9, 59);
    lv_obj_set_align(ui_PanelDIGITAL9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel9 = lv_label_create(ui_PanelDIGITAL9);
    lv_obj_set_width(ui_DIGITALLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel9, -96);
    lv_obj_set_y(ui_DIGITALLabel9, 1);
    lv_obj_set_align(ui_DIGITALLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel9, "DIGITAL 9 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel9, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus9 = lv_label_create(ui_PanelDIGITAL9);
    lv_obj_set_width(ui_digitalstatus9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus9, 117);
    lv_obj_set_y(ui_digitalstatus9, 0);
    lv_obj_set_align(ui_digitalstatus9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus9, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDIGITAL10 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDIGITAL10, 378);
    lv_obj_set_height(ui_PanelDIGITAL10, 52);
    lv_obj_set_x(ui_PanelDIGITAL10, 195);
    lv_obj_set_y(ui_PanelDIGITAL10, 123);
    lv_obj_set_align(ui_PanelDIGITAL10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDIGITAL10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIGITALLabel10 = lv_label_create(ui_PanelDIGITAL10);
    lv_obj_set_width(ui_DIGITALLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIGITALLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIGITALLabel10, -96);
    lv_obj_set_y(ui_DIGITALLabel10, 1);
    lv_obj_set_align(ui_DIGITALLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIGITALLabel10, "DIGITAL 10 STATUS");
    lv_obj_set_style_text_color(ui_DIGITALLabel10, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIGITALLabel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIGITALLabel10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digitalstatus10 = lv_label_create(ui_PanelDIGITAL10);
    lv_obj_set_width(ui_digitalstatus10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_digitalstatus10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_digitalstatus10, 117);
    lv_obj_set_y(ui_digitalstatus10, 0);
    lv_obj_set_align(ui_digitalstatus10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digitalstatus10, "OFF");
    lv_obj_set_style_text_font(ui_digitalstatus10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_fueltitlepanel3 = NULL;
    ui_fuellabeltitle3 = NULL;
    ui_PanelDIGITAL1 = NULL;
    ui_DIGITALLabel1 = NULL;
    ui_digitalstatus1 = NULL;
    ui_PanelDIGITAL2 = NULL;
    ui_DIGITALLabel2 = NULL;
    ui_digitalstatus2 = NULL;
    ui_PanelDIGITAL3 = NULL;
    ui_DIGITALLabel3 = NULL;
    ui_digitalstatus3 = NULL;
    ui_PanelDIGITAL4 = NULL;
    ui_DIGITALLabel4 = NULL;
    ui_digitalstatus4 = NULL;
    ui_PanelDIGITAL5 = NULL;
    ui_DIGITALLabel5 = NULL;
    ui_digitalstatus5 = NULL;
    ui_PanelDIGITAL6 = NULL;
    ui_DIGITALLabel6 = NULL;
    ui_digitalstatus6 = NULL;
    ui_PanelDIGITAL7 = NULL;
    ui_DIGITALLabel7 = NULL;
    ui_digitalstatus7 = NULL;
    ui_PanelDIGITAL8 = NULL;
    ui_DIGITALLabel8 = NULL;
    ui_digitalstatus8 = NULL;
    ui_PanelDIGITAL9 = NULL;
    ui_DIGITALLabel9 = NULL;
    ui_digitalstatus9 = NULL;
    ui_PanelDIGITAL10 = NULL;
    ui_DIGITALLabel10 = NULL;
    ui_digitalstatus10 = NULL;

}
