// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_fueltitlepanel;
extern lv_obj_t * ui_fuellabeltitle;
extern lv_obj_t * ui_PanelLambda;
extern lv_obj_t * ui_lambda;
extern lv_obj_t * ui_LambdaLabel;
extern lv_obj_t * ui_PanelLambdatarget;
extern lv_obj_t * ui_lambdatarget;
extern lv_obj_t * ui_LambdaLabel1;
extern lv_obj_t * ui_Panelfuel;
extern lv_obj_t * ui_FUELLabel;
extern lv_obj_t * ui_fuel;
extern lv_obj_t * ui_PaneLCorrlamb;
extern lv_obj_t * ui_CORRLAMBDALabel1;
extern lv_obj_t * ui_correctionlambda;
extern lv_obj_t * ui_PanelETC2;
extern lv_obj_t * ui_ect2;
extern lv_obj_t * ui_ECTlabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

