// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_fueltitlepanel3;
extern lv_obj_t * ui_fuellabeltitle3;
extern lv_obj_t * ui_PanelDIGITAL1;
extern lv_obj_t * ui_DIGITALLabel1;
extern lv_obj_t * ui_digitalstatus1;
extern lv_obj_t * ui_PanelDIGITAL2;
extern lv_obj_t * ui_DIGITALLabel2;
extern lv_obj_t * ui_digitalstatus2;
extern lv_obj_t * ui_PanelDIGITAL3;
extern lv_obj_t * ui_DIGITALLabel3;
extern lv_obj_t * ui_digitalstatus3;
extern lv_obj_t * ui_PanelDIGITAL4;
extern lv_obj_t * ui_DIGITALLabel4;
extern lv_obj_t * ui_digitalstatus4;
extern lv_obj_t * ui_PanelDIGITAL5;
extern lv_obj_t * ui_DIGITALLabel5;
extern lv_obj_t * ui_digitalstatus5;
extern lv_obj_t * ui_PanelDIGITAL6;
extern lv_obj_t * ui_DIGITALLabel6;
extern lv_obj_t * ui_digitalstatus6;
extern lv_obj_t * ui_PanelDIGITAL7;
extern lv_obj_t * ui_DIGITALLabel7;
extern lv_obj_t * ui_digitalstatus7;
extern lv_obj_t * ui_PanelDIGITAL8;
extern lv_obj_t * ui_DIGITALLabel8;
extern lv_obj_t * ui_digitalstatus8;
extern lv_obj_t * ui_PanelDIGITAL9;
extern lv_obj_t * ui_DIGITALLabel9;
extern lv_obj_t * ui_digitalstatus9;
extern lv_obj_t * ui_PanelDIGITAL10;
extern lv_obj_t * ui_DIGITALLabel10;
extern lv_obj_t * ui_digitalstatus10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

