// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_fueltitlepanel2;
extern lv_obj_t * ui_fuellabeltitle2;
extern lv_obj_t * ui_PanelAUX1;
extern lv_obj_t * ui_AUXLabel1;
extern lv_obj_t * ui_auxstatus1;
extern lv_obj_t * ui_PanelAUX2;
extern lv_obj_t * ui_AUXLabel2;
extern lv_obj_t * ui_auxstatus2;
extern lv_obj_t * ui_PanelAUX3;
extern lv_obj_t * ui_AUXLabel3;
extern lv_obj_t * ui_auxstatus3;
extern lv_obj_t * ui_PanelAUX4;
extern lv_obj_t * ui_AUXLabel4;
extern lv_obj_t * ui_auxstatus4;
extern lv_obj_t * ui_PanelAUX5;
extern lv_obj_t * ui_AUXLabel5;
extern lv_obj_t * ui_auxstatus5;
extern lv_obj_t * ui_PanelAUX6;
extern lv_obj_t * ui_AUXLabel6;
extern lv_obj_t * ui_auxstatus6;
extern lv_obj_t * ui_PanelAUX7;
extern lv_obj_t * ui_AUXLabel7;
extern lv_obj_t * ui_auxstatus7;
extern lv_obj_t * ui_PanelAUX8;
extern lv_obj_t * ui_AUXLabel8;
extern lv_obj_t * ui_auxstatus8;
extern lv_obj_t * ui_PanelAUX9;
extern lv_obj_t * ui_AUXLabel9;
extern lv_obj_t * ui_auxstatus9;
extern lv_obj_t * ui_PanelAUX10;
extern lv_obj_t * ui_AUXLabel10;
extern lv_obj_t * ui_auxstatus10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

