// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PanelGear;
extern lv_obj_t * ui_gear;
extern lv_obj_t * ui_PanelRPM;
extern lv_obj_t * ui_rpm;
extern lv_obj_t * ui_PanelBATT;
extern lv_obj_t * ui_battvoltlabel;
extern lv_obj_t * ui_battvolt;
extern lv_obj_t * ui_PanelETC;
extern lv_obj_t * ui_ect;
extern lv_obj_t * ui_ECTlabel;
extern lv_obj_t * ui_PanelSHUTDOWN;
extern lv_obj_t * ui_SHUTDOWN_LABEL;
extern lv_obj_t * ui_shutdown;
extern lv_obj_t * ui_PanelFAN;
extern lv_obj_t * ui_FANLabel;
extern lv_obj_t * ui_fan;

// RPM LED Bar - 16 mini panels
extern lv_obj_t * ui_RPMBar1;
extern lv_obj_t * ui_RPMBar2;
extern lv_obj_t * ui_RPMBar3;
extern lv_obj_t * ui_RPMBar4;
extern lv_obj_t * ui_RPMBar5;
extern lv_obj_t * ui_RPMBar6;
extern lv_obj_t * ui_RPMBar7;
extern lv_obj_t * ui_RPMBar8;
extern lv_obj_t * ui_RPMBar9;
extern lv_obj_t * ui_RPMBar10;
extern lv_obj_t * ui_RPMBar11;
extern lv_obj_t * ui_RPMBar12;
extern lv_obj_t * ui_RPMBar13;
extern lv_obj_t * ui_RPMBar14;
extern lv_obj_t * ui_RPMBar15;
extern lv_obj_t * ui_RPMBar16;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

